/**
 * JSON-LD, generated from the database. W-SITE-03.
 *
 * `buildStructuredDataGraph` is the only entry point a page needs; everything else is exported because a
 * test asserts a property of it, or because the validator and the CI script share it.
 */
export {
  areaServedNodes,
  businessId,
  END_OF_DAY,
  geoNode,
  IN_STOCK,
  isOpenAt,
  localBusinessNode,
  openingHoursSpecifications,
  organizationId,
  organizationNode,
  postalAddressNode,
  SAME_AS_KINDS,
  SAME_AS_UNANSWERED,
  type SameAsKind,
  type SameAsProfile,
  SCHEMA_DAY_NAMES,
  START_OF_DAY,
  telephoneOf,
} from './business.ts'
export {
  type BreadcrumbStep,
  breadcrumbId,
  breadcrumbListNode,
  type FaqEntry,
  faqPageId,
  faqPageNode,
  type HeroImage,
  type HeroVideo,
  imageObjectId,
  imageObjectNode,
  mayPublishTherapist,
  type PersonNodesOptions,
  personId,
  personNodeFor,
  personNodesFor,
  type TherapistCandidate,
  type TherapistPublishingRefusal,
  therapistPublishingRefusals,
  videoObjectId,
  videoObjectNode,
} from './content.ts'
export {
  buildStructuredDataGraph,
  type StructuredDataInput,
  serialiseGraph,
} from './graph.ts'
export {
  durationValue,
  grossMoneyFromFils,
  grossPriceString,
  offerId,
  offerIdsIn,
  type PricedOfferInput,
  pricedOfferFor,
  pricedOffersIn,
  priceOnRequestOfferFor,
  priceOnRequestOfferId,
  type ServiceNodesOptions,
  serviceId,
  serviceNodes,
  slugifyLabel,
} from './offerings.ts'
export {
  SPECIMEN_BREADCRUMB,
  SPECIMEN_CLOSES,
  SPECIMEN_FAQ,
  SPECIMEN_OPENS,
  SPECIMEN_ORIGIN,
  SPECIMEN_PAGE_URL,
  SPECIMEN_THERAPISTS,
  type SpecimenGraph,
  specimenFacts,
  specimenGraphs,
} from './specimen.ts'
export {
  type BreadcrumbListNode,
  type FaqPageNode,
  type GeoCoordinatesNode,
  GRAPH_RULES,
  type GraphRule,
  type ImageObjectNode,
  type LocalBusinessNode,
  NO_NULLS_RULE,
  type OfferNode,
  type OpeningHoursSpecificationNode,
  type OrganizationNode,
  type PersonNode,
  type PlaceNode,
  type PostalAddressNode,
  type PricedOfferNode,
  type PriceOnRequestOfferNode,
  type QuestionNode,
  SCHEMA_CONTEXT,
  type ServiceNode,
  type SiteNode,
  type StructuredDataGraph,
  type VideoObjectNode,
} from './types.ts'
export {
  formatFindings,
  type GraphFinding,
  graphOpenAt,
  type ValidateGraphOptions,
  validateGraph,
} from './validate.ts'
export {
  assertVocabularyPermitted,
  businessTypesFor,
  LICENCE_CLASSES,
  type LicenceClass,
  MEDICAL_VOCABULARY,
  type MedicalTerm,
  medicalTermsIn,
  medicalVocabularyPermitted,
  PRIMARY_BUSINESS_TYPE,
  personTypesFor,
  serviceTypesFor,
} from './vocabulary.ts'
