/**
 * GENERATED by scripts/palette.py. Do not edit.
 *
 * Every value here was derived by walking a prototype colour along its own hue and
 * saturation until it met a stated contrast ratio, and every one is re-measured on each CI
 * run. Editing a hex by hand fails `pnpm palette` — which is the point: a designer changing a
 * token by eye is how a palette stops meeting the ratios it claims.
 *
 * Regenerate with `pnpm palette:emit`.
 */

/**
 * Light theme. Pastels and sands carry surfaces; ink and accents carry text.
 *
 * Ground is `#FDFAF5`.
 */
export const LIGHT_PALETTE = {
  /** 1.0:1 against the ground — surface or decorative only. */
  'ground': '#FDFAF5',
  /** 1.04:1 against the ground — surface or decorative only. */
  'surface': '#FFFFFF',
  /** 1.04:1 against the ground — surface or decorative only. */
  'surface-raised': '#FFFFFF',
  /** 1.09:1 against the ground — surface or decorative only. */
  'ground-sunk': '#F7F0E5',
  /** 1.15:1 against the ground — surface or decorative only. */
  'surface-sand': '#F2E9DC',
  /** 1.35:1 against the ground — surface or decorative only. */
  'surface-clay': '#E6D8C4',
  /** 14.89:1 against the ground — requires 4.5:1. */
  'ink': '#26241F',
  /** 5.36:1 against the ground — requires 4.5:1. */
  'ink-2': '#6E675D',
  /** 3.4:1 against the ground — requires 3.0:1. */
  'ink-3': '#90877B',
  /** 4.62:1 against the ground — requires 4.5:1. */
  'accent-gold': '#946A32',
  /** 7.26:1 against the ground — requires 7.0:1. */
  'accent-gold-strong': '#6E4E25',
  /** 5.4:1 against the ground — requires 4.5:1. */
  'accent-green': '#4E7048',
  /** 5.73:1 against the ground — requires 4.5:1. */
  'accent-teal': '#2A6E66',
  /** 2.9:1 against the ground — surface or decorative only. */
  'decor-gold': '#C08A43',
  /** 2.04:1 against the ground — surface or decorative only. */
  'decor-tan': '#C9AE8B',
  /** 1.35:1 against the ground — surface or decorative only. */
  'hairline': '#E6D8C4',
  /** 2.04:1 against the ground — surface or decorative only. */
  'border': '#C9AE8B',
  /** 3.04:1 against the ground — requires 3.0:1. */
  'border-strong': '#B18A57',
  /** 5.73:1 against the ground — requires 3.0:1. */
  'focus': '#2A6E66',
  /** 5.22:1 against the ground — requires 4.5:1. */
  'danger': '#C0392B',
  /** 5.4:1 against the ground — requires 4.5:1. */
  'success': '#4E7048',
} as const

/**
 * Dark theme, warm rather than inverted. Accent polarity flips: the bright brand gold is unusable for text in light mode and is the primary accent here.
 *
 * Ground is `#141210`.
 */
export const DARK_PALETTE = {
  /** 1.0:1 against the ground — surface or decorative only. */
  'ground': '#141210',
  /** 1.04:1 against the ground — surface or decorative only. */
  'ground-sunk': '#0F0D0B',
  /** 1.1:1 against the ground — surface or decorative only. */
  'surface': '#1F1C18',
  /** 1.23:1 against the ground — surface or decorative only. */
  'surface-raised': '#292520',
  /** 1.14:1 against the ground — surface or decorative only. */
  'surface-sand': '#231F1A',
  /** 1.31:1 against the ground — surface or decorative only. */
  'surface-clay': '#2F2A24',
  /** 15.75:1 against the ground — requires 4.5:1. */
  'ink': '#F0EBE3',
  /** 8.5:1 against the ground — requires 4.5:1. */
  'ink-2': '#B5AEA4',
  /** 3.74:1 against the ground — requires 3.0:1. */
  'ink-3': '#746F66',
  /** 6.19:1 against the ground — requires 4.5:1. */
  'accent-gold': '#C08A43',
  /** 7.03:1 against the ground — requires 7.0:1. */
  'accent-gold-strong': '#C69656',
  /** 4.63:1 against the ground — requires 4.5:1. */
  'accent-green': '#5F8958',
  /** 4.64:1 against the ground — requires 4.5:1. */
  'accent-teal': '#358C81',
  /** 6.19:1 against the ground — surface or decorative only. */
  'decor-gold': '#C08A43',
  /** 8.82:1 against the ground — surface or decorative only. */
  'decor-tan': '#C9AE8B',
  /** 1.24:1 against the ground — surface or decorative only. */
  'hairline': '#2A2621',
  /** 1.54:1 against the ground — surface or decorative only. */
  'border': '#3A352E',
  /** 5.11:1 against the ground — requires 3.0:1. */
  'border-strong': '#8B857B',
  /** 7.95:1 against the ground — requires 3.0:1. */
  'focus': '#5FB8AC',
  /** 4.53:1 against the ground — requires 4.5:1. */
  'danger': '#D55144',
  /** 4.63:1 against the ground — requires 4.5:1. */
  'success': '#5F8958',
} as const

/** Measured contrast against each theme's ground, for the tests and the docs gate. */
export const PALETTE_RATIOS = {
  light: {
    'ground': 1.0,
    'surface': 1.04,
    'surface-raised': 1.04,
    'ground-sunk': 1.09,
    'surface-sand': 1.15,
    'surface-clay': 1.35,
    'ink': 14.89,
    'ink-2': 5.36,
    'ink-3': 3.4,
    'accent-gold': 4.62,
    'accent-gold-strong': 7.26,
    'accent-green': 5.4,
    'accent-teal': 5.73,
    'decor-gold': 2.9,
    'decor-tan': 2.04,
    'hairline': 1.35,
    'border': 2.04,
    'border-strong': 3.04,
    'focus': 5.73,
    'danger': 5.22,
    'success': 5.4,
  },
  dark: {
    'ground': 1.0,
    'ground-sunk': 1.04,
    'surface': 1.1,
    'surface-raised': 1.23,
    'surface-sand': 1.14,
    'surface-clay': 1.31,
    'ink': 15.75,
    'ink-2': 8.5,
    'ink-3': 3.74,
    'accent-gold': 6.19,
    'accent-gold-strong': 7.03,
    'accent-green': 4.63,
    'accent-teal': 4.64,
    'decor-gold': 6.19,
    'decor-tan': 8.82,
    'hairline': 1.24,
    'border': 1.54,
    'border-strong': 5.11,
    'focus': 7.95,
    'danger': 4.53,
    'success': 4.63,
  },
} as const
