import {
  isWithinPlaceholderBand,
  PLACEHOLDER_CHROMA_MAX,
  PLACEHOLDER_LIGHTNESS_MAX,
  PLACEHOLDER_LIGHTNESS_MIN,
  rgbToOklch,
} from '@berelax/media/placeholder'
import { EDITABLE_SLOT_NAMES, MEDIA_SLOT_LIST, slotPlaceholderColour } from '@berelax/media/slots'
import { describe, expect, it } from 'vitest'
import { DARK_PALETTE, LIGHT_PALETTE } from './palette.generated.ts'

/**
 * "Palette-matched placeholder" as a measurement rather than a claim.
 *
 * Each slot's placeholder is a palette **token name** (see `packages/media/src/slots/registry.ts`), which
 * is what keeps the literal colour out of it and what makes the dark theme resolve for free. What that
 * leaves to be proved is the part a token name cannot state: that the colour behind the name actually sits
 * inside docs/08 §6's OKLCH band — chroma ≤0.06, lightness 0.86–0.94 — so the swap to the photograph is not
 * a flash and the card does not tint the page it sits on.
 *
 * This is the one file that can prove it. `@berelax/media` measures colours and must not depend on the
 * palette; the palette is generated by `scripts/palette.py` and knows nothing about media. The token layer
 * is where the two meet.
 *
 * The control is unusually strong and it is free: only three of the twenty-one light token names are inside
 * the band at all — and two of those are the same hex — so the eighteen outside it are eighteen deliberate
 * counter-examples. A band that admitted everything would fail here.
 */
function oklchOf(hex: string) {
  return rgbToOklch({
    r: Number.parseInt(hex.slice(1, 3), 16),
    g: Number.parseInt(hex.slice(3, 5), 16),
    b: Number.parseInt(hex.slice(5, 7), 16),
  })
}

/** The token name out of `var(--color-x)`, which is the only form the registry returns. */
function tokenOf(slot: (typeof MEDIA_SLOT_LIST)[number]): string {
  const css = slotPlaceholderColour(slot.name)
  const match = /^var\(--color-([a-z0-9-]+)\)$/.exec(css)
  expect(match, `${slot.name} placeholder is not a palette custom property: ${css}`).not.toBeNull()
  return match?.[1] ?? ''
}

describe('every slot placeholder is a palette colour inside the OKLCH band', () => {
  it('names a token the palette actually defines', () => {
    for (const slot of MEDIA_SLOT_LIST) {
      if (slot.placeholder === null) continue
      const token = tokenOf(slot)
      expect(Object.hasOwn(LIGHT_PALETTE, token), `${slot.name} -> ${token}`).toBe(true)
      // Both themes, because the placeholder is referenced by name and the dark theme redefines the same
      // custom property — a token the dark palette lacked would resolve to nothing in a dark document.
      expect(Object.hasOwn(DARK_PALETTE, token), `${slot.name} -> ${token}`).toBe(true)
    }
  })

  it('measures inside chroma <= 0.06 and lightness 0.86..0.94 in the light theme', () => {
    for (const slot of MEDIA_SLOT_LIST) {
      if (slot.placeholder === null) continue
      const token = tokenOf(slot)
      const colour = oklchOf(LIGHT_PALETTE[token as keyof typeof LIGHT_PALETTE])
      expect(isWithinPlaceholderBand(colour), `${slot.name} -> ${token}`).toBe(true)
      expect(colour.chroma, token).toBeLessThanOrEqual(PLACEHOLDER_CHROMA_MAX)
      expect(colour.lightness, token).toBeGreaterThanOrEqual(PLACEHOLDER_LIGHTNESS_MIN)
      expect(colour.lightness, token).toBeLessThanOrEqual(PLACEHOLDER_LIGHTNESS_MAX)
    }
  })

  it('has eighteen counter-examples in the same palette', () => {
    // The control. docs/08 §6's band is narrow, and this says so: `surface-sand` and `surface-clay` (and
    // `hairline`, which is the same hex as `surface-clay`) are the only tokens inside it. `ground` at
    // L=0.986 is too light to read as a placeholder at all and `ink` at L=0.261 would flash black.
    const inBand = Object.entries(LIGHT_PALETTE).filter(([, hex]) =>
      isWithinPlaceholderBand(oklchOf(hex)),
    )
    expect(inBand.map(([name]) => name).sort()).toEqual([
      'hairline',
      'surface-clay',
      'surface-sand',
    ])
    expect(Object.keys(LIGHT_PALETTE).length - inBand.length).toBe(18)
    expect(isWithinPlaceholderBand(oklchOf(LIGHT_PALETTE.ground))).toBe(false)
    expect(isWithinPlaceholderBand(oklchOf(LIGHT_PALETTE.ink))).toBe(false)
  })

  it('is stated as a light-theme band, which is what docs/08 §6 measured', () => {
    // Worth writing down rather than discovering: the band is a light band by construction — lightness
    // 0.86–0.94 — and the dark palette's surfaces run from L=0.161 to L=0.288, so none of them can be
    // inside it. The placeholder follows the theme because it is referenced by token name, and the band is
    // the light theme's version of the same decision. A dark-theme band is a Y12-photos question.
    for (const [, hex] of Object.entries(DARK_PALETTE)) {
      const colour = oklchOf(hex)
      if (colour.lightness >= PLACEHOLDER_LIGHTNESS_MIN) continue
      expect(isWithinPlaceholderBand(colour)).toBe(false)
    }
    const darkTokens = MEDIA_SLOT_LIST.filter((slot) => slot.placeholder !== null).map((slot) =>
      oklchOf(DARK_PALETTE[tokenOf(slot) as keyof typeof DARK_PALETTE]),
    )
    expect(darkTokens.every((colour) => colour.lightness < PLACEHOLDER_LIGHTNESS_MIN)).toBe(true)
  })

  it('covers all five of docs/08 §6’s named slots', () => {
    const covered = MEDIA_SLOT_LIST.filter((slot) => slot.placeholder !== null).map(
      (slot) => slot.name,
    )
    expect(covered).toEqual([...EDITABLE_SLOT_NAMES])
  })
})
