/**
 * @berelax/db — Drizzle schema, migrations and repositories.
 *
 * Hard constraints, enforced by `pnpm boundaries`:
 *   - may import @berelax/shared only
 *   - MUST NOT import @berelax/core (dependency direction is core <- db, never db -> core)
 */

export {
  type Actor,
  type ActorKind,
  type AuditOperation,
  type AuditRecord,
  AuditWriter,
  type RequestContext,
} from './audit.ts'
export {
  type ConnectionOptions,
  createConnection,
  REQUIRED_EXTENSIONS,
  type Sql,
} from './connection.ts'
export {
  createJobQueue,
  DEFAULT_QUEUE_OPTIONS,
  type JobQueueOptions,
  MAINTENANCE_JOBS,
  PGBOSS_SCHEMA,
} from './jobs/boss.ts'
export {
  type BusinessDayInput,
  businessDayFingerprint,
  type GenerationResult,
  generateBusinessDays,
  type WriteOptions,
} from './jobs/generate-business-days.ts'
export {
  type DomainEvent,
  type DrainResult,
  drainOutbox,
  type EventHandler,
  type HandlerRegistration,
  outboxBacklog,
  publishEvent,
  type StoredEvent,
} from './outbox.ts'
export {
  bucketTotalFils,
  type OutstandingPayable,
  outstandingPayables,
  overdueTotalFils,
  PAYABLES_AGING_BUCKETS,
  type PayablesAgingBucket,
  type PayablesAgingReport,
  type PayablesAgingRow,
  payablesAging,
} from './queries/payables-aging.ts'
export {
  type ForecastFilter,
  type ForecastPeriod,
  type ForecastRow,
  forecastPeriodTotalFils,
  type RecurringCostForecast,
  recurringCostForecast,
  recurringCostSchedule,
} from './queries/recurring-cost-forecast.ts'
export {
  isBalanced,
  type TrialBalance,
  type TrialBalanceRow,
  trialBalanceAsAt,
  trialBalanceMovement,
} from './queries/trial-balance.ts'
export {
  type AgentDefinitionRow,
  type AgentHeartbeatRow,
  type AgentOutcome,
  type AgentRunResult,
  type AlertToRaise,
  agentsWithHeartbeat,
  findAgent,
  openAlerts,
  type RunBody,
  type RunOptions,
  raiseAlert,
  recordHeartbeat,
  setEnabled,
  setKillSwitch,
  withAgentRun,
} from './repositories/agents.ts'
export {
  archiveService,
  assertPublicDisplayNameLinted,
  CATALOGUE_REFUSALS,
  CATALOGUE_SQLSTATE,
  type CatalogueRefusal,
  type CompliancePolicyRow,
  catalogueError,
  changeVariantPrice,
  deleteService,
  listBookableServices,
  type PathResolution,
  type PriceChange,
  type PriceChangeInput,
  type PublicDisplayNameLint,
  publishService,
  type RenameSlugResult,
  readCompliancePolicy,
  readService,
  refusalOf,
  renameServiceSlug,
  resolveServicePath,
  SERVICE_PATH_PREFIX,
  type ServiceSnapshot,
  type SetPublicDisplayNameInput,
  servicePath,
  setInternalName,
  setPublicDisplayName,
  TREATMENTS_INDEX_PATH,
} from './repositories/catalogue.ts'
export {
  CUSTOMER_ORIGINS,
  type CustomerIdentityInput,
  type CustomerOrigin,
  type CustomerRecord,
  type EnsureCustomerResult,
  ensureCustomer,
  findCustomerByPhone,
  markPhoneVerified,
} from './repositories/customer.ts'
export {
  type EligibilityQueryInput,
  type EligibleTherapistRow,
  EXCLUSION_REASONS,
  type ExcludedTherapistRow,
  type ExclusionReason,
  exclusionReasonFrom,
  readCommittedAppointments,
  readEligibleTherapists,
  readMandatoryDocumentTypes,
  type ScheduledAppointmentRow,
  type TherapistPoolRead,
  type TherapistShiftRow,
} from './repositories/eligibility.ts'
export {
  type CustomerSnapshotInput,
  INVOICE_DOCUMENT_KINDS,
  INVOICE_SQLSTATE,
  type InvoiceDocumentKind,
  type InvoiceLineInput,
  type IssuedInvoice,
  type IssuedInvoiceLine,
  type IssueInvoiceInput,
  type IssuerSnapshotInput,
  invoiceError,
  isInvoiceAppendOnly,
  isInvoiceTotalsDisagreement,
  issueInvoice,
  type MandatoryInvoiceField,
  readInvoice,
  readInvoiceByDisplayNumber,
  Y11_VAT_INVOICE_FIELDS,
} from './repositories/invoice.ts'
export {
  type AccountBalanceRow,
  accountTotals,
  isAppendOnlyViolation,
  isPeriodLocked,
  isUnbalancedEntry,
  JOURNAL_SQLSTATE,
  type JournalEntryInput,
  type JournalLineInput,
  journalError,
  listPeriodLocks,
  lockAccountingPeriod,
  type PeriodLockInput,
  type PeriodLockRow,
  type PostedJournalEntry,
  type PostedJournalLine,
  periodLockFor,
  postJournalEntry,
  readChartOfAccounts,
  readJournalEntry,
  type StoredAccount,
  type StoredChartOfAccounts,
  type StoredProvisionalMarker,
} from './repositories/journal.ts'
export {
  type AllocatedDocumentNumber,
  allocateDocumentNumber,
  DOCUMENT_SERIES_CODES,
  type DocumentSeriesCode,
  type DocumentSeriesRow,
  findNumberingGaps,
  listDocumentSeries,
  NUMBERING_LEDGER_COLUMNS,
  type NumberingGap,
} from './repositories/numbering.ts'
export {
  generateOtpCode,
  hashOtpCode,
  issueOtpChallenge,
  OTP_CODE_DIGITS,
  OTP_IP_WINDOW_MINUTES,
  OTP_LOCK_MINUTES,
  OTP_MAX_FAILED_ATTEMPTS,
  OTP_MAX_REQUESTS_PER_IP,
  OTP_MAX_REQUESTS_PER_PHONE,
  OTP_PHONE_WINDOW_MINUTES,
  OTP_PURPOSES,
  OTP_RATE_LIMITS,
  OTP_TTL_MINUTES,
  OTP_VERIFY_REJECTIONS,
  type OtpIssueRequest,
  type OtpIssueResult,
  type OtpPurpose,
  type OtpRateLimit,
  type OtpVerifyRejection,
  type OtpVerifyRequest,
  type OtpVerifyResult,
  verifyOtpCode,
} from './repositories/otp.ts'
export {
  type ApiIngestOutcome,
  type ApiReviewPayload,
  getReview,
  type IngestedReview,
  ingestApiReview,
  listReviewQueue,
  type ManualReviewInput,
  type QueuedReview,
  type ReconciliationInput,
  type ReconciliationOutcome,
  reconcileApiReviewId,
  recordManualReview,
  recordReplyConfirmedByGoogle,
  recordReplyPostedManually,
  recordReplySubmittedToApi,
} from './repositories/reviews.ts'
export * as schema from './schema/index.ts'
export {
  type CatalogueSeedResult,
  PRICE_ON_REQUEST_SEED,
  seedCatalogue,
} from './seed/catalogue.ts'
export {
  comparePriceCells,
  DOCS_13_PRICE_POINT_COUNT,
  DOCS_13_PRICES_AED,
  type Docs13PriceCell,
  docs13PriceCells,
  FILS_PER_AED,
  type PriceMismatch,
  type StoredPricePoint,
} from './seed/fixtures/prices-docs-13.ts'
export {
  PROVISIONAL_OPENING_DATE,
  PROVISIONAL_OPENING_LINES,
  seedProvisionalOpeningBalances,
} from './seed/opening-balances.ts'
export {
  ensureLegalEntity,
  LEGAL_ENTITY_ID,
  LEGAL_ENTITY_SEED,
  PREMISES_ID,
  PREMISES_NAP,
  seedPremises,
  TRADING_CLOSE_TIME,
  TRADING_DAYS_OF_WEEK,
  TRADING_OPEN_TIME,
  WHATSAPP_CANDIDATES,
  WHATSAPP_PENDING,
} from './seed/premises.ts'
export {
  type ImportedOpeningBalances,
  importOpeningBalances,
  isBeforeOpeningBalance,
  OPENING_BALANCE_SQLSTATE,
  type OpeningBalanceImport,
  type OpeningBalanceLine,
  openingDate,
  openingImbalanceFils,
  provisionalOpeningBalances,
} from './services/opening-balances.ts'
export {
  BILL_SERIES_CODE,
  BILL_TAX_TREATMENTS,
  type BillLineToPost,
  type BillTaxTreatment,
  type BillToPost,
  findSupplierByCode,
  isDuplicateSupplierReference,
  isInputVatWithoutTrn,
  PLACE_OF_SUPPLY_RULES,
  type PlaceOfSupplyRule,
  type PostedBill,
  type PostedBillLine,
  PURCHASES_SQLSTATE,
  postBill,
  purchaseError,
  RECOVERABLE_INPUT_VAT_ACCOUNT_CODE,
  readBill,
  recordSupplier,
  SUPPLIER_RESIDENCIES,
  type SupplierInput,
  type SupplierRecord,
  type SupplierResidency,
  TRADE_PAYABLES_ACCOUNT_CODE,
} from './services/post-bill.ts'
export {
  findRecurringCostByCode,
  type GeneratedInstance,
  type GenerateWindow,
  generateRecurringInstances,
  isDuplicateRecurringCostMatch,
  type MatchInput,
  type MatchResult,
  matchBillToRecurringCost,
  type PeriodStatus,
  type PostedRecurringBill,
  postRecurringBill,
  type RaisedAlert,
  RECURRING_CADENCES,
  RECURRING_COST_ALERT_KINDS,
  RECURRING_COST_KINDS,
  RECURRING_COST_SQLSTATE,
  type RecurringBillToPost,
  type RecurringCadence,
  type RecurringCostAlertKind,
  type RecurringCostInput,
  type RecurringCostKind,
  type RecurringCostRecord,
  recordRecurringCost,
  recurringCostError,
  recurringCostPeriodStatus,
  sweepRecurringCostAlerts,
  tradingDateAt,
} from './services/recurring-cost.ts'
export {
  type UnconfirmedAssumptionRow,
  unconfirmedAssumptionRows,
} from './settings-store.ts'
export { type UnitOfWork, withUnitOfWork } from './tx.ts'

export const SCHEMA_VERSION = 32 as const
