/**
 * @berelax/core — pure domain logic. Availability, pricing, VAT, leave accrual,
 * commission, ledger rules.
 *
 * Hard constraints, enforced by `pnpm boundaries`:
 *   - may import @berelax/shared only
 *   - MUST NOT import @berelax/db, any app, any framework, or any I/O
 *   - MUST NOT read the clock directly; time is always injected
 */

export * from './access/permissions.ts'
export * from './access/principal-policy.ts'
export * from './access/principals/customer-link.ts'
export * from './access/principals/front-desk-diary.ts'
export * from './access/principals/registry.ts'
export * from './access/principals/seo-agent.ts'
export * from './access/publication.ts'
export * from './agents/index.ts'
export * from './alerts/evaluate.ts'
export * from './analytics/index.ts'
export { assertNever } from './assert-never.ts'
export * from './automation/index.ts'
export * from './availability/index.ts'
export * from './booking/index.ts'
export * from './business-day/index.ts'
export * from './calendar/index.ts'
export * from './checkout/index.ts'
export * from './clinical/contraindication-flags.ts'
export * from './clinical/intake.ts'
export * from './compliance/index.ts'
export * from './consent/index.ts'
export * from './crm/index.ts'
export * from './documents/invoice-template.ts'
export * from './documents/private-document.ts'
export * from './google/index.ts'
export * from './hr/attendance.ts'
export * from './hr/commission.ts'
export * from './hr/credentials.ts'
export * from './hr/employee.ts'
export * from './hr/gratuity.ts'
export * from './hr/holiday-impact.ts'
export * from './hr/labour-cost.ts'
export * from './hr/leave-accrual.ts'
export * from './hr/leave-approval.ts'
export * from './hr/payroll.ts'
export * from './hr/rates.ts'
export * from './hr/reassignment.ts'
export * from './hr/rota-validator.ts'
export * from './hr/sick-leave.ts'
export * from './hr/working-hours.ts'
export * from './hr/wps-sif.ts'
export * from './identity/index.ts'
export * from './ledger/index.ts'
export * from './lifecycle/index.ts'
export * from './messaging/encoding.ts'
export * from './messaging/frequency-cap.ts'
export * from './messaging/promotional-window.ts'
export * from './messaging/retry.ts'
export * from './messaging/segments.ts'
export * from './money/cash-up.ts'
export * from './money/package-drawdown.ts'
export * from './money/package-terms.ts'
export * from './money/recurring-schedule.ts'
export * from './money/tender.ts'
export * from './money/vat.ts'
export * from './money.ts'
export * from './payments/index.ts'
export * from './pricing/index.ts'
export * from './privacy/processor-policy.ts'
export * from './privacy/rights-policy.ts'
export * from './publication/index.ts'
export * from './purchases/index.ts'
export * from './reporting/cac.ts'
export * from './reporting/cash-forecast.ts'
export * from './reporting/cohort-kpi-probe.ts'
export * from './reporting/cohorts.ts'
export * from './reporting/contribution-margin.ts'
export * from './reporting/kpi-expression.ts'
export * from './reporting/kpi-registry.ts'
export * from './reporting/operational-kpis.ts'
export * from './reporting/package-liability.ts'
export * from './reporting/revpar.ts'
export * from './reporting/seasonality.ts'
export * from './reporting/statements.ts'
export * from './reporting/utilisation.ts'
export * from './reviews/index.ts'
export * from './seo/index.ts'
export * from './tax/index.ts'
export * from './text/index.ts'
export * from './time.ts'
