/**
 * @berelax/ui — design tokens, and later the components built on them.
 *
 * Today this is tokens only. The palette is generated by `scripts/palette.py` and re-derived on every
 * CI run; the scales are hand-authored from docs/08. Both emit CSS from one place, so the web, the
 * transactional emails and the generated PDFs cannot disagree about what a colour is.
 */

export { tokensCss } from './tokens/emit.ts'
export * from './tokens/index.ts'
