/**
 * @berelax/ui — design tokens, and later the components built on them.
 *
 * Today this is tokens only. The palette is generated by `scripts/palette.py` and re-derived on every
 * CI run; the scales are hand-authored from docs/08. Both emit CSS from one place, so the web, the
 * transactional emails and the generated PDFs cannot disagree about what a colour is.
 *
 * `ThemeProvider` is **not** re-exported here. It is a React component, so it is a `.tsx` file, and the
 * root typecheck project deliberately has neither `jsx` nor the DOM lib — that absence is what keeps a
 * `document.querySelector` from compiling inside `packages/core`. Re-exporting it from this barrel pulls
 * the `.tsx` into every project that imports a colour token. It lives at `@berelax/ui/theme-provider`,
 * which only an app imports.
 */

export {
  type Direction,
  directionFor,
  type Locale,
  MOTION_STORAGE_KEY,
  THEME_ATTRIBUTE,
  THEME_STORAGE_KEY,
  type ThemePreference,
  themeAttributeFor,
  themeBootstrapScript,
} from './theme/theme.ts'
export { tokensCss } from './tokens/emit.ts'
export * from './tokens/index.ts'
