/*
 * Generated by `payload migrate:create`, with ONE edit: the two `Migrate*Args` names are imported as
 * TYPES. Payload's generator emits them as a value import, and `@payloadcms/db-postgres` exports them as
 * types only — so at run time ESM refuses the module with "does not provide an export named
 * 'MigrateDownArgs'" and `payload migrate` cannot read its own migration file. Re-generating this file
 * will reintroduce it; the same two lines fix it again.
 */
import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres'
import { sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "payload"."enum_cms_user_role" AS ENUM('owner', 'manager', 'accountant', 'receptionist', 'therapist', 'marketer', 'auditor', 'system');
  CREATE TYPE "payload"."enum_pages_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__pages_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_journal_posts_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__journal_posts_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_faq_entries_topic" AS ENUM('visiting', 'treatments', 'booking', 'health', 'payment');
  CREATE TYPE "payload"."enum_faq_entries_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__faq_entries_v_version_topic" AS ENUM('visiting', 'treatments', 'booking', 'health', 'payment');
  CREATE TYPE "payload"."enum__faq_entries_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_service_narrative_editorial_state" AS ENUM('live', 'archived');
  CREATE TYPE "payload"."enum_service_narrative_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__service_narrative_v_version_editorial_state" AS ENUM('live', 'archived');
  CREATE TYPE "payload"."enum__service_narrative_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_therapist_narrative_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__therapist_narrative_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_testimonials_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__testimonials_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_media_slot" AS ENUM('hero', 'therapist-portrait', 'service-card', 'gallery', 'testimonial-background', 'logo');
  CREATE TYPE "payload"."enum_compliance_notices_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__compliance_notices_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum_editorial_defaults_status" AS ENUM('draft', 'published');
  CREATE TYPE "payload"."enum__editorial_defaults_v_version_status" AS ENUM('draft', 'published');
  CREATE TABLE "payload"."cms_user_sessions" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"created_at" timestamp(3) with time zone,
  	"expires_at" timestamp(3) with time zone NOT NULL
  );
  
  CREATE TABLE "payload"."cms_user" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"role" "payload"."enum_cms_user_role" NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"email" varchar NOT NULL,
  	"reset_password_token" varchar,
  	"reset_password_expiration" timestamp(3) with time zone,
  	"salt" varchar,
  	"hash" varchar,
  	"login_attempts" numeric DEFAULT 0,
  	"lock_until" timestamp(3) with time zone
  );
  
  CREATE TABLE "payload"."pages" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"slug" varchar,
  	"title" varchar,
  	"lede" varchar,
  	"body" jsonb,
  	"seo_title" varchar,
  	"seo_description" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_pages_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_pages_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version_slug" varchar,
  	"version_title" varchar,
  	"version_lede" varchar,
  	"version_body" jsonb,
  	"version_seo_title" varchar,
  	"version_seo_description" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__pages_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."journal_posts" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"slug" varchar,
  	"title" varchar,
  	"standfirst" varchar,
  	"body" jsonb,
  	"published_on" timestamp(3) with time zone,
  	"byline" varchar,
  	"reviewed_by" varchar,
  	"health_topic" boolean,
  	"seo_title" varchar,
  	"seo_description" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_journal_posts_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_journal_posts_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version_slug" varchar,
  	"version_title" varchar,
  	"version_standfirst" varchar,
  	"version_body" jsonb,
  	"version_published_on" timestamp(3) with time zone,
  	"version_byline" varchar,
  	"version_reviewed_by" varchar,
  	"version_health_topic" boolean,
  	"version_seo_title" varchar,
  	"version_seo_description" varchar,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__journal_posts_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."faq_entries" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"_order" varchar,
  	"question" varchar,
  	"answer" jsonb,
  	"topic" "payload"."enum_faq_entries_topic",
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_faq_entries_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_faq_entries_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version__order" varchar,
  	"version_question" varchar,
  	"version_answer" jsonb,
  	"version_topic" "payload"."enum__faq_entries_v_version_topic",
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__faq_entries_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."service_narrative" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"catalogue_service_id" varchar,
  	"slug" varchar,
  	"headline" varchar,
  	"promise" varchar,
  	"body" jsonb,
  	"aftercare" varchar,
  	"seo_title" varchar,
  	"seo_description" varchar,
  	"editorial_state" "payload"."enum_service_narrative_editorial_state",
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_service_narrative_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_service_narrative_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version_catalogue_service_id" varchar,
  	"version_slug" varchar,
  	"version_headline" varchar,
  	"version_promise" varchar,
  	"version_body" jsonb,
  	"version_aftercare" varchar,
  	"version_seo_title" varchar,
  	"version_seo_description" varchar,
  	"version_editorial_state" "payload"."enum__service_narrative_v_version_editorial_state",
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__service_narrative_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."therapist_narrative_languages" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"language" varchar
  );
  
  CREATE TABLE "payload"."therapist_narrative" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"therapist_id" varchar,
  	"approach" varchar,
  	"narrative" jsonb,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_therapist_narrative_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_therapist_narrative_v_version_languages" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" uuid PRIMARY KEY NOT NULL,
  	"language" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "payload"."_therapist_narrative_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version_therapist_id" varchar,
  	"version_approach" varchar,
  	"version_narrative" jsonb,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__therapist_narrative_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."testimonials" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"quote" varchar,
  	"attribution_initials" varchar,
  	"catalogue_service_id" varchar,
  	"consent_recorded" boolean DEFAULT false,
  	"published_on" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"_status" "payload"."enum_testimonials_status" DEFAULT 'draft'
  );
  
  CREATE TABLE "payload"."_testimonials_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"parent_id" uuid,
  	"version_quote" varchar,
  	"version_attribution_initials" varchar,
  	"version_catalogue_service_id" varchar,
  	"version_consent_recorded" boolean DEFAULT false,
  	"version_published_on" timestamp(3) with time zone,
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"version__status" "payload"."enum__testimonials_v_version_status" DEFAULT 'draft',
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."media_alt_context" (
  	"_order" integer NOT NULL,
  	"_parent_id" uuid NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"phrase" varchar NOT NULL
  );
  
  CREATE TABLE "payload"."media" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"slot" "payload"."enum_media_slot" NOT NULL,
  	"alt" varchar,
  	"decorative" boolean,
  	"credit" varchar,
  	"derivative_manifest" jsonb,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"url" varchar,
  	"thumbnail_u_r_l" varchar,
  	"filename" varchar,
  	"mime_type" varchar,
  	"filesize" numeric,
  	"width" numeric,
  	"height" numeric,
  	"focal_x" numeric,
  	"focal_y" numeric
  );
  
  CREATE TABLE "payload"."payload_kv" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"key" varchar NOT NULL,
  	"data" jsonb NOT NULL
  );
  
  CREATE TABLE "payload"."payload_locked_documents" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"global_slug" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload"."payload_locked_documents_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"cms_user_id" uuid,
  	"pages_id" uuid,
  	"journal_posts_id" uuid,
  	"faq_entries_id" uuid,
  	"service_narrative_id" uuid,
  	"therapist_narrative_id" uuid,
  	"testimonials_id" uuid,
  	"media_id" uuid
  );
  
  CREATE TABLE "payload"."payload_preferences" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"key" varchar,
  	"value" jsonb,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload"."payload_preferences_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" uuid NOT NULL,
  	"path" varchar NOT NULL,
  	"cms_user_id" uuid
  );
  
  CREATE TABLE "payload"."payload_migrations" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"name" varchar,
  	"batch" numeric,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "payload"."compliance_notices" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"medical_disclaimer" jsonb,
  	"licence_statement" varchar,
  	"complaints_procedure" jsonb,
  	"last_reviewed_on" timestamp(3) with time zone,
  	"_status" "payload"."enum_compliance_notices_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "payload"."_compliance_notices_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"version_medical_disclaimer" jsonb,
  	"version_licence_statement" varchar,
  	"version_complaints_procedure" jsonb,
  	"version_last_reviewed_on" timestamp(3) with time zone,
  	"version__status" "payload"."enum__compliance_notices_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "payload"."editorial_defaults" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"default_seo_title" varchar,
  	"default_seo_description" varchar,
  	"journal_index_blurb" varchar,
  	"_status" "payload"."enum_editorial_defaults_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "payload"."_editorial_defaults_v" (
  	"id" uuid PRIMARY KEY NOT NULL,
  	"version_default_seo_title" varchar,
  	"version_default_seo_description" varchar,
  	"version_journal_index_blurb" varchar,
  	"version__status" "payload"."enum__editorial_defaults_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  ALTER TABLE "payload"."cms_user_sessions" ADD CONSTRAINT "cms_user_sessions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "payload"."cms_user"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."_pages_v" ADD CONSTRAINT "_pages_v_parent_id_pages_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."pages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."_journal_posts_v" ADD CONSTRAINT "_journal_posts_v_parent_id_journal_posts_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."journal_posts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."_faq_entries_v" ADD CONSTRAINT "_faq_entries_v_parent_id_faq_entries_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."faq_entries"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."_service_narrative_v" ADD CONSTRAINT "_service_narrative_v_parent_id_service_narrative_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."service_narrative"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."therapist_narrative_languages" ADD CONSTRAINT "therapist_narrative_languages_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "payload"."therapist_narrative"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."_therapist_narrative_v_version_languages" ADD CONSTRAINT "_therapist_narrative_v_version_languages_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "payload"."_therapist_narrative_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."_therapist_narrative_v" ADD CONSTRAINT "_therapist_narrative_v_parent_id_therapist_narrative_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."therapist_narrative"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."_testimonials_v" ADD CONSTRAINT "_testimonials_v_parent_id_testimonials_id_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."testimonials"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload"."media_alt_context" ADD CONSTRAINT "media_alt_context_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "payload"."media"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."payload_locked_documents"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_cms_user_fk" FOREIGN KEY ("cms_user_id") REFERENCES "payload"."cms_user"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "payload"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_journal_posts_fk" FOREIGN KEY ("journal_posts_id") REFERENCES "payload"."journal_posts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_faq_entries_fk" FOREIGN KEY ("faq_entries_id") REFERENCES "payload"."faq_entries"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_service_narrative_fk" FOREIGN KEY ("service_narrative_id") REFERENCES "payload"."service_narrative"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_therapist_narrative_fk" FOREIGN KEY ("therapist_narrative_id") REFERENCES "payload"."therapist_narrative"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_testimonials_fk" FOREIGN KEY ("testimonials_id") REFERENCES "payload"."testimonials"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "payload"."media"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "payload"."payload_preferences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload"."payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_cms_user_fk" FOREIGN KEY ("cms_user_id") REFERENCES "payload"."cms_user"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "cms_user_sessions_order_idx" ON "payload"."cms_user_sessions" USING btree ("_order");
  CREATE INDEX "cms_user_sessions_parent_id_idx" ON "payload"."cms_user_sessions" USING btree ("_parent_id");
  CREATE INDEX "cms_user_updated_at_idx" ON "payload"."cms_user" USING btree ("updated_at");
  CREATE INDEX "cms_user_created_at_idx" ON "payload"."cms_user" USING btree ("created_at");
  CREATE UNIQUE INDEX "cms_user_email_idx" ON "payload"."cms_user" USING btree ("email");
  CREATE UNIQUE INDEX "pages_slug_idx" ON "payload"."pages" USING btree ("slug");
  CREATE INDEX "pages_updated_at_idx" ON "payload"."pages" USING btree ("updated_at");
  CREATE INDEX "pages_created_at_idx" ON "payload"."pages" USING btree ("created_at");
  CREATE INDEX "pages__status_idx" ON "payload"."pages" USING btree ("_status");
  CREATE INDEX "_pages_v_parent_idx" ON "payload"."_pages_v" USING btree ("parent_id");
  CREATE INDEX "_pages_v_version_version_slug_idx" ON "payload"."_pages_v" USING btree ("version_slug");
  CREATE INDEX "_pages_v_version_version_updated_at_idx" ON "payload"."_pages_v" USING btree ("version_updated_at");
  CREATE INDEX "_pages_v_version_version_created_at_idx" ON "payload"."_pages_v" USING btree ("version_created_at");
  CREATE INDEX "_pages_v_version_version__status_idx" ON "payload"."_pages_v" USING btree ("version__status");
  CREATE INDEX "_pages_v_created_at_idx" ON "payload"."_pages_v" USING btree ("created_at");
  CREATE INDEX "_pages_v_updated_at_idx" ON "payload"."_pages_v" USING btree ("updated_at");
  CREATE INDEX "_pages_v_latest_idx" ON "payload"."_pages_v" USING btree ("latest");
  CREATE UNIQUE INDEX "journal_posts_slug_idx" ON "payload"."journal_posts" USING btree ("slug");
  CREATE INDEX "journal_posts_updated_at_idx" ON "payload"."journal_posts" USING btree ("updated_at");
  CREATE INDEX "journal_posts_created_at_idx" ON "payload"."journal_posts" USING btree ("created_at");
  CREATE INDEX "journal_posts__status_idx" ON "payload"."journal_posts" USING btree ("_status");
  CREATE INDEX "_journal_posts_v_parent_idx" ON "payload"."_journal_posts_v" USING btree ("parent_id");
  CREATE INDEX "_journal_posts_v_version_version_slug_idx" ON "payload"."_journal_posts_v" USING btree ("version_slug");
  CREATE INDEX "_journal_posts_v_version_version_updated_at_idx" ON "payload"."_journal_posts_v" USING btree ("version_updated_at");
  CREATE INDEX "_journal_posts_v_version_version_created_at_idx" ON "payload"."_journal_posts_v" USING btree ("version_created_at");
  CREATE INDEX "_journal_posts_v_version_version__status_idx" ON "payload"."_journal_posts_v" USING btree ("version__status");
  CREATE INDEX "_journal_posts_v_created_at_idx" ON "payload"."_journal_posts_v" USING btree ("created_at");
  CREATE INDEX "_journal_posts_v_updated_at_idx" ON "payload"."_journal_posts_v" USING btree ("updated_at");
  CREATE INDEX "_journal_posts_v_latest_idx" ON "payload"."_journal_posts_v" USING btree ("latest");
  CREATE INDEX "faq_entries__order_idx" ON "payload"."faq_entries" USING btree ("_order");
  CREATE INDEX "faq_entries_updated_at_idx" ON "payload"."faq_entries" USING btree ("updated_at");
  CREATE INDEX "faq_entries_created_at_idx" ON "payload"."faq_entries" USING btree ("created_at");
  CREATE INDEX "faq_entries__status_idx" ON "payload"."faq_entries" USING btree ("_status");
  CREATE INDEX "_faq_entries_v_parent_idx" ON "payload"."_faq_entries_v" USING btree ("parent_id");
  CREATE INDEX "_faq_entries_v_version_version__order_idx" ON "payload"."_faq_entries_v" USING btree ("version__order");
  CREATE INDEX "_faq_entries_v_version_version_updated_at_idx" ON "payload"."_faq_entries_v" USING btree ("version_updated_at");
  CREATE INDEX "_faq_entries_v_version_version_created_at_idx" ON "payload"."_faq_entries_v" USING btree ("version_created_at");
  CREATE INDEX "_faq_entries_v_version_version__status_idx" ON "payload"."_faq_entries_v" USING btree ("version__status");
  CREATE INDEX "_faq_entries_v_created_at_idx" ON "payload"."_faq_entries_v" USING btree ("created_at");
  CREATE INDEX "_faq_entries_v_updated_at_idx" ON "payload"."_faq_entries_v" USING btree ("updated_at");
  CREATE INDEX "_faq_entries_v_latest_idx" ON "payload"."_faq_entries_v" USING btree ("latest");
  CREATE INDEX "service_narrative_catalogue_service_id_idx" ON "payload"."service_narrative" USING btree ("catalogue_service_id");
  CREATE UNIQUE INDEX "service_narrative_slug_idx" ON "payload"."service_narrative" USING btree ("slug");
  CREATE INDEX "service_narrative_updated_at_idx" ON "payload"."service_narrative" USING btree ("updated_at");
  CREATE INDEX "service_narrative_created_at_idx" ON "payload"."service_narrative" USING btree ("created_at");
  CREATE INDEX "service_narrative__status_idx" ON "payload"."service_narrative" USING btree ("_status");
  CREATE INDEX "_service_narrative_v_parent_idx" ON "payload"."_service_narrative_v" USING btree ("parent_id");
  CREATE INDEX "_service_narrative_v_version_version_catalogue_service_i_idx" ON "payload"."_service_narrative_v" USING btree ("version_catalogue_service_id");
  CREATE INDEX "_service_narrative_v_version_version_slug_idx" ON "payload"."_service_narrative_v" USING btree ("version_slug");
  CREATE INDEX "_service_narrative_v_version_version_updated_at_idx" ON "payload"."_service_narrative_v" USING btree ("version_updated_at");
  CREATE INDEX "_service_narrative_v_version_version_created_at_idx" ON "payload"."_service_narrative_v" USING btree ("version_created_at");
  CREATE INDEX "_service_narrative_v_version_version__status_idx" ON "payload"."_service_narrative_v" USING btree ("version__status");
  CREATE INDEX "_service_narrative_v_created_at_idx" ON "payload"."_service_narrative_v" USING btree ("created_at");
  CREATE INDEX "_service_narrative_v_updated_at_idx" ON "payload"."_service_narrative_v" USING btree ("updated_at");
  CREATE INDEX "_service_narrative_v_latest_idx" ON "payload"."_service_narrative_v" USING btree ("latest");
  CREATE INDEX "therapist_narrative_languages_order_idx" ON "payload"."therapist_narrative_languages" USING btree ("_order");
  CREATE INDEX "therapist_narrative_languages_parent_id_idx" ON "payload"."therapist_narrative_languages" USING btree ("_parent_id");
  CREATE INDEX "therapist_narrative_therapist_id_idx" ON "payload"."therapist_narrative" USING btree ("therapist_id");
  CREATE INDEX "therapist_narrative_updated_at_idx" ON "payload"."therapist_narrative" USING btree ("updated_at");
  CREATE INDEX "therapist_narrative_created_at_idx" ON "payload"."therapist_narrative" USING btree ("created_at");
  CREATE INDEX "therapist_narrative__status_idx" ON "payload"."therapist_narrative" USING btree ("_status");
  CREATE INDEX "_therapist_narrative_v_version_languages_order_idx" ON "payload"."_therapist_narrative_v_version_languages" USING btree ("_order");
  CREATE INDEX "_therapist_narrative_v_version_languages_parent_id_idx" ON "payload"."_therapist_narrative_v_version_languages" USING btree ("_parent_id");
  CREATE INDEX "_therapist_narrative_v_parent_idx" ON "payload"."_therapist_narrative_v" USING btree ("parent_id");
  CREATE INDEX "_therapist_narrative_v_version_version_therapist_id_idx" ON "payload"."_therapist_narrative_v" USING btree ("version_therapist_id");
  CREATE INDEX "_therapist_narrative_v_version_version_updated_at_idx" ON "payload"."_therapist_narrative_v" USING btree ("version_updated_at");
  CREATE INDEX "_therapist_narrative_v_version_version_created_at_idx" ON "payload"."_therapist_narrative_v" USING btree ("version_created_at");
  CREATE INDEX "_therapist_narrative_v_version_version__status_idx" ON "payload"."_therapist_narrative_v" USING btree ("version__status");
  CREATE INDEX "_therapist_narrative_v_created_at_idx" ON "payload"."_therapist_narrative_v" USING btree ("created_at");
  CREATE INDEX "_therapist_narrative_v_updated_at_idx" ON "payload"."_therapist_narrative_v" USING btree ("updated_at");
  CREATE INDEX "_therapist_narrative_v_latest_idx" ON "payload"."_therapist_narrative_v" USING btree ("latest");
  CREATE INDEX "testimonials_catalogue_service_id_idx" ON "payload"."testimonials" USING btree ("catalogue_service_id");
  CREATE INDEX "testimonials_updated_at_idx" ON "payload"."testimonials" USING btree ("updated_at");
  CREATE INDEX "testimonials_created_at_idx" ON "payload"."testimonials" USING btree ("created_at");
  CREATE INDEX "testimonials__status_idx" ON "payload"."testimonials" USING btree ("_status");
  CREATE INDEX "_testimonials_v_parent_idx" ON "payload"."_testimonials_v" USING btree ("parent_id");
  CREATE INDEX "_testimonials_v_version_version_catalogue_service_id_idx" ON "payload"."_testimonials_v" USING btree ("version_catalogue_service_id");
  CREATE INDEX "_testimonials_v_version_version_updated_at_idx" ON "payload"."_testimonials_v" USING btree ("version_updated_at");
  CREATE INDEX "_testimonials_v_version_version_created_at_idx" ON "payload"."_testimonials_v" USING btree ("version_created_at");
  CREATE INDEX "_testimonials_v_version_version__status_idx" ON "payload"."_testimonials_v" USING btree ("version__status");
  CREATE INDEX "_testimonials_v_created_at_idx" ON "payload"."_testimonials_v" USING btree ("created_at");
  CREATE INDEX "_testimonials_v_updated_at_idx" ON "payload"."_testimonials_v" USING btree ("updated_at");
  CREATE INDEX "_testimonials_v_latest_idx" ON "payload"."_testimonials_v" USING btree ("latest");
  CREATE INDEX "media_alt_context_order_idx" ON "payload"."media_alt_context" USING btree ("_order");
  CREATE INDEX "media_alt_context_parent_id_idx" ON "payload"."media_alt_context" USING btree ("_parent_id");
  CREATE INDEX "media_updated_at_idx" ON "payload"."media" USING btree ("updated_at");
  CREATE INDEX "media_created_at_idx" ON "payload"."media" USING btree ("created_at");
  CREATE UNIQUE INDEX "media_filename_idx" ON "payload"."media" USING btree ("filename");
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload"."payload_kv" USING btree ("key");
  CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload"."payload_locked_documents" USING btree ("global_slug");
  CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload"."payload_locked_documents" USING btree ("updated_at");
  CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload"."payload_locked_documents" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload"."payload_locked_documents_rels" USING btree ("order");
  CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload"."payload_locked_documents_rels" USING btree ("parent_id");
  CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload"."payload_locked_documents_rels" USING btree ("path");
  CREATE INDEX "payload_locked_documents_rels_cms_user_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("cms_user_id");
  CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("pages_id");
  CREATE INDEX "payload_locked_documents_rels_journal_posts_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("journal_posts_id");
  CREATE INDEX "payload_locked_documents_rels_faq_entries_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("faq_entries_id");
  CREATE INDEX "payload_locked_documents_rels_service_narrative_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("service_narrative_id");
  CREATE INDEX "payload_locked_documents_rels_therapist_narrative_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("therapist_narrative_id");
  CREATE INDEX "payload_locked_documents_rels_testimonials_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("testimonials_id");
  CREATE INDEX "payload_locked_documents_rels_media_id_idx" ON "payload"."payload_locked_documents_rels" USING btree ("media_id");
  CREATE INDEX "payload_preferences_key_idx" ON "payload"."payload_preferences" USING btree ("key");
  CREATE INDEX "payload_preferences_updated_at_idx" ON "payload"."payload_preferences" USING btree ("updated_at");
  CREATE INDEX "payload_preferences_created_at_idx" ON "payload"."payload_preferences" USING btree ("created_at");
  CREATE INDEX "payload_preferences_rels_order_idx" ON "payload"."payload_preferences_rels" USING btree ("order");
  CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload"."payload_preferences_rels" USING btree ("parent_id");
  CREATE INDEX "payload_preferences_rels_path_idx" ON "payload"."payload_preferences_rels" USING btree ("path");
  CREATE INDEX "payload_preferences_rels_cms_user_id_idx" ON "payload"."payload_preferences_rels" USING btree ("cms_user_id");
  CREATE INDEX "payload_migrations_updated_at_idx" ON "payload"."payload_migrations" USING btree ("updated_at");
  CREATE INDEX "payload_migrations_created_at_idx" ON "payload"."payload_migrations" USING btree ("created_at");
  CREATE INDEX "compliance_notices__status_idx" ON "payload"."compliance_notices" USING btree ("_status");
  CREATE INDEX "_compliance_notices_v_version_version__status_idx" ON "payload"."_compliance_notices_v" USING btree ("version__status");
  CREATE INDEX "_compliance_notices_v_created_at_idx" ON "payload"."_compliance_notices_v" USING btree ("created_at");
  CREATE INDEX "_compliance_notices_v_updated_at_idx" ON "payload"."_compliance_notices_v" USING btree ("updated_at");
  CREATE INDEX "_compliance_notices_v_latest_idx" ON "payload"."_compliance_notices_v" USING btree ("latest");
  CREATE INDEX "editorial_defaults__status_idx" ON "payload"."editorial_defaults" USING btree ("_status");
  CREATE INDEX "_editorial_defaults_v_version_version__status_idx" ON "payload"."_editorial_defaults_v" USING btree ("version__status");
  CREATE INDEX "_editorial_defaults_v_created_at_idx" ON "payload"."_editorial_defaults_v" USING btree ("created_at");
  CREATE INDEX "_editorial_defaults_v_updated_at_idx" ON "payload"."_editorial_defaults_v" USING btree ("updated_at");
  CREATE INDEX "_editorial_defaults_v_latest_idx" ON "payload"."_editorial_defaults_v" USING btree ("latest");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "payload"."cms_user_sessions" CASCADE;
  DROP TABLE "payload"."cms_user" CASCADE;
  DROP TABLE "payload"."pages" CASCADE;
  DROP TABLE "payload"."_pages_v" CASCADE;
  DROP TABLE "payload"."journal_posts" CASCADE;
  DROP TABLE "payload"."_journal_posts_v" CASCADE;
  DROP TABLE "payload"."faq_entries" CASCADE;
  DROP TABLE "payload"."_faq_entries_v" CASCADE;
  DROP TABLE "payload"."service_narrative" CASCADE;
  DROP TABLE "payload"."_service_narrative_v" CASCADE;
  DROP TABLE "payload"."therapist_narrative_languages" CASCADE;
  DROP TABLE "payload"."therapist_narrative" CASCADE;
  DROP TABLE "payload"."_therapist_narrative_v_version_languages" CASCADE;
  DROP TABLE "payload"."_therapist_narrative_v" CASCADE;
  DROP TABLE "payload"."testimonials" CASCADE;
  DROP TABLE "payload"."_testimonials_v" CASCADE;
  DROP TABLE "payload"."media_alt_context" CASCADE;
  DROP TABLE "payload"."media" CASCADE;
  DROP TABLE "payload"."payload_kv" CASCADE;
  DROP TABLE "payload"."payload_locked_documents" CASCADE;
  DROP TABLE "payload"."payload_locked_documents_rels" CASCADE;
  DROP TABLE "payload"."payload_preferences" CASCADE;
  DROP TABLE "payload"."payload_preferences_rels" CASCADE;
  DROP TABLE "payload"."payload_migrations" CASCADE;
  DROP TABLE "payload"."compliance_notices" CASCADE;
  DROP TABLE "payload"."_compliance_notices_v" CASCADE;
  DROP TABLE "payload"."editorial_defaults" CASCADE;
  DROP TABLE "payload"."_editorial_defaults_v" CASCADE;
  DROP TYPE "payload"."enum_cms_user_role";
  DROP TYPE "payload"."enum_pages_status";
  DROP TYPE "payload"."enum__pages_v_version_status";
  DROP TYPE "payload"."enum_journal_posts_status";
  DROP TYPE "payload"."enum__journal_posts_v_version_status";
  DROP TYPE "payload"."enum_faq_entries_topic";
  DROP TYPE "payload"."enum_faq_entries_status";
  DROP TYPE "payload"."enum__faq_entries_v_version_topic";
  DROP TYPE "payload"."enum__faq_entries_v_version_status";
  DROP TYPE "payload"."enum_service_narrative_editorial_state";
  DROP TYPE "payload"."enum_service_narrative_status";
  DROP TYPE "payload"."enum__service_narrative_v_version_editorial_state";
  DROP TYPE "payload"."enum__service_narrative_v_version_status";
  DROP TYPE "payload"."enum_therapist_narrative_status";
  DROP TYPE "payload"."enum__therapist_narrative_v_version_status";
  DROP TYPE "payload"."enum_testimonials_status";
  DROP TYPE "payload"."enum__testimonials_v_version_status";
  DROP TYPE "payload"."enum_media_slot";
  DROP TYPE "payload"."enum_compliance_notices_status";
  DROP TYPE "payload"."enum__compliance_notices_v_version_status";
  DROP TYPE "payload"."enum_editorial_defaults_status";
  DROP TYPE "payload"."enum__editorial_defaults_v_version_status";`)
}
