-- 0019 — phone-first customer identity, and the OTP challenge that proves possession of the number.
--
-- ADR 0014: customers have no accounts. There is no password column anywhere in this file and there
-- never will be one; identity is the phone number, and the phone number is proved by a code sent to
-- it. Three decisions carry the migration.
--
-- ## The canonical number is UNIQUE, and the match keys are not
--
-- `phone_e164` is the identity, so it is UNIQUE: two spellings of one number must collide on insert
-- rather than produce two customers whose history, package balance and contraindication flags each
-- hold half the truth. The match keys are for the MERGE that C-CRM will own, which is a different
-- job: it looks for rows that are PROBABLY the same person and asks a human. A unique index there
-- would refuse the very rows the merge exists to find.
--
-- `phone_match_key` is generated by the database because it is the trailing nine digits of a value the
-- database already holds; a derivation that trivial belongs where it cannot drift. `name_match_key` is
-- written by the application because the normalisation behind it folds Arabic orthography and sorts
-- the words, `unaccent` is STABLE and so cannot appear in a generated column at all, and a plpgsql
-- re-implementation would give one match key two definitions. The day they disagreed, the merge would
-- silently stop finding duplicates. `packages/core/src/identity/normalise-phone.ts` is the single
-- definition, and packages/fixtures/src/customer-identity.itest.ts asserts the generated column and
-- the TypeScript agree on a table of spellings.
--
-- ## An OTP challenge is not a credential
--
-- `otp_challenge.phone_e164` is deliberately NOT a foreign key to `customer`. A challenge must exist
-- for a number nobody has seen before: that is what makes an OTP request for a known number and for an
-- unknown one indistinguishable, which is the enumeration-resistance requirement. A foreign key would
-- force the request path to create a customer row for every number anybody types, which hands an
-- attacker a way to fill the customer table and turns the OTP endpoint into a customer generator.
--
-- The code itself is stored as a salted hash and NOTHING here holds it in the clear. The window is
-- five minutes and the code is six digits, so a table dump taken during that window is enough to walk
-- in as the customer; a hash makes the dump worthless. A schema test asserts by information_schema
-- that no plaintext column exists, because a `code` column added later "just for debugging" is exactly
-- how this ends up in a backup.
--
-- ## The failed-attempt counter is per PHONE, not per challenge
--
-- Five failed attempts lock the phone for fifteen minutes. If that counter lived on the challenge
-- row, an attacker would request a new code every five guesses and the limit would be unlimited
-- guesses. So it lives in `otp_phone_lock`, keyed by the number, and requesting a new code does not
-- reset it.

begin;

-- --------------------------------------------------------------------------------------------------
-- The customer.
-- --------------------------------------------------------------------------------------------------

create table customer (
  id                uuid        primary key default uuid_generate_v7(),
  -- Canonical E.164, produced by normalisePhone at the boundary. The check is a shape check rather
  -- than a UAE-mobile check on purpose: it catches an un-normalised value written straight into the
  -- column, which is the failure that splits one person into several rows, without teaching the
  -- database a prefix list that the regulator changes without telling anybody.
  phone_e164        text        not null unique
                      constraint customer_phone_is_e164 check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  -- Trailing nine digits: the length of a UAE national significant number. Generated, so a hand
  -- written INSERT cannot produce a row the merge cannot see.
  phone_match_key   text        not null
                      generated always as (right(regexp_replace(phone_e164, '[^0-9]', '', 'g'), 9)) stored,
  -- Null until somebody enters one. No name is ever invented for a customer: the fixtures and the UI
  -- label a record `Customer 0042`, which cannot be mistaken for a person (ADR 0020).
  display_name      text,
  -- normalised-name + last-4, written by the application from packages/core. Null when there is no
  -- name, because a key built from the digits alone would match every customer sharing a last-four.
  name_match_key    text,
  locale            text        not null default 'en' check (locale in ('en','ar')),
  -- When the number was last proved by an OTP. NULL is the ordinary state for a guest booking: a
  -- booking is taken on an unverified number exactly as the paper diary took it, and verification is
  -- required only to READ something back (history, clinical flags).
  phone_verified_at timestamptz,
  -- How the record came into being, so an unexpected population of rows can be traced to a path.
  created_via       text        not null default 'guest_booking'
                      check (created_via in ('guest_booking','front_desk','otp_verification','import')),
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table customer is
  'Phone-first identity, no accounts and no credentials (ADR 0014). phone_e164 is UNIQUE because it '
  'IS the identity; the match keys are indexed but not unique because they feed the merge C-CRM owns.';
comment on column customer.phone_match_key is
  'Generated: trailing nine digits of phone_e164. The merge candidate key, for rows imported without '
  'a country code. Never the identity - that is phone_e164.';
comment on column customer.name_match_key is
  'normalised-name + last-4, written by the application. Not generated: the normalisation folds '
  'Arabic orthography and sorts words, and unaccent is STABLE so it cannot appear in a generated '
  'column. One definition, in packages/core.';
comment on column customer.phone_verified_at is
  'Null for a guest booking. Verification gates reading data back, never taking a booking.';

create index customer_phone_match_key_idx on customer (phone_match_key);
create index customer_name_match_key_idx on customer (name_match_key)
  where name_match_key is not null;
-- Fuzzy duplicate detection on the written name, which is why pg_trgm is installed (0001).
create index customer_display_name_trgm_idx on customer using gin (display_name gin_trgm_ops);

create trigger customer_updated_at before update on customer
  for each row execute function set_updated_at();

-- --------------------------------------------------------------------------------------------------
-- The OTP challenge.
-- --------------------------------------------------------------------------------------------------

create type otp_purpose as enum ('booking_verify', 'view_bookings', 'clinical_flags');
comment on type otp_purpose is
  'What the code is being requested for. An enum because a code issued to confirm a booking must not '
  'be replayable to read clinical flags, and a free-text purpose is a purpose nobody can rely on.';

create table otp_challenge (
  id              uuid         primary key default uuid_generate_v7(),
  -- Not a foreign key, and not nullable. See the header: a challenge for an unknown number must
  -- exist, or a known and an unknown number are distinguishable by whether the request succeeded.
  phone_e164      text         not null
                    constraint otp_challenge_phone_is_e164 check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  purpose         otp_purpose  not null,
  -- HMAC-SHA-256 of the code under a per-row random salt. There is no column holding the code.
  code_hash       bytea        not null,
  code_salt       bytea        not null,
  -- Both supplied by the caller from an injected clock rather than defaulted to now(): every
  -- assertion about expiry in this unit is made under a frozen clock, and a column that reads the
  -- wall clock cannot be tested at all without waiting five real minutes.
  issued_at       timestamptz  not null,
  expires_at      timestamptz  not null,
  -- Single use. Set on the successful verification, and a second attempt with the same code fails.
  consumed_at     timestamptz,
  -- Set when a newer challenge replaces this one. Two live codes for one number means an intercepted
  -- earlier SMS keeps working, which is the failure a resend button quietly introduces.
  superseded_at   timestamptz,
  failed_attempts smallint     not null default 0 check (failed_attempts >= 0),
  -- Who asked, as far as the edge can tell. inet, so the per-IP rate limit is an index scan and not
  -- a string comparison. Null when the header is absent rather than invented.
  request_ip      inet,
  request_id      text,
  created_at      timestamptz  not null default now(),
  constraint otp_challenge_expires_after_issue check (expires_at > issued_at)
);

comment on table otp_challenge is
  'One row per issued code. The code is never stored: code_hash is an HMAC under code_salt, and a '
  'schema test asserts by information_schema that no plaintext column exists.';
comment on column otp_challenge.phone_e164 is
  'Deliberately not a foreign key to customer. A challenge for an unknown number must exist, or the '
  'endpoint tells an attacker which numbers are customers.';
comment on column otp_challenge.superseded_at is
  'Set when a newer code is issued for the same number and purpose. Only the newest code verifies.';

-- The per-phone rate limit and the newest-live-challenge lookup are the same index.
create index otp_challenge_phone_idx on otp_challenge (phone_e164, issued_at desc);
-- The per-IP rate limit. Partial, because a null ip is not a bucket.
create index otp_challenge_ip_idx on otp_challenge (request_ip, issued_at desc)
  where request_ip is not null;

-- --------------------------------------------------------------------------------------------------
-- The per-phone failure lock.
-- --------------------------------------------------------------------------------------------------

create table otp_phone_lock (
  phone_e164           text        primary key
                         constraint otp_phone_lock_phone_is_e164 check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  -- Reset by a successful verification and by the lock expiring. NOT reset by requesting a new code:
  -- that is what makes five attempts a limit rather than a suggestion.
  consecutive_failures smallint    not null default 0 check (consecutive_failures >= 0),
  locked_until         timestamptz,
  last_failure_at      timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on table otp_phone_lock is
  'Failed OTP attempts per NUMBER, not per challenge. A counter on the challenge row would let an '
  'attacker request a fresh code every five guesses and guess forever.';

create trigger otp_phone_lock_updated_at before update on otp_phone_lock
  for each row execute function set_updated_at();

commit;
