/**
 * @berelax/media — the derivative pipeline, immutable media URLs and the storage port.
 *
 * Importing this barrel pulls in `sharp`, and therefore libvips. Anything that runs in a browser — the
 * `next/image` loader above all — must import `@berelax/media/loader`, `/ladders` or `/url` instead,
 * which are the sharp-free halves.
 */
export {
  type BuildDerivativesInput,
  buildDerivatives,
  CENTRE_FOCAL,
  type DerivativeBuildResult,
  type DerivativeOutput,
  encodeRendition,
  type FocalPoint,
  isOriginalKey,
  type RenditionRequest,
  readSourceGeometry,
  type SourceGeometry,
  storeOriginal,
} from './derivatives.ts'
export { contentAddress, sha256Hex } from './hash.ts'
export {
  AVIF_OPTIONS,
  CONTENT_TYPES,
  CROP_NAMES,
  CROPS,
  type CropLadder,
  type CropName,
  type CropRect,
  cropRectFor,
  type DerivativeFormat,
  FORMATS,
  heightFor,
  isDeclaredWidth,
  JPEG_OPTIONS,
  nearestRung,
  type RenditionSpec,
  renditionSpecs,
  WEBP_OPTIONS,
} from './ladders.ts'
export {
  type ImageLoaderArgs,
  MAX_REQUESTED_WIDTH,
  mediaImageLoader,
  servedWidth,
} from './loader.ts'
export {
  isWithinPlaceholderBand,
  type Oklch,
  PLACEHOLDER_CHROMA_MAX,
  PLACEHOLDER_LIGHTNESS_MAX,
  PLACEHOLDER_LIGHTNESS_MIN,
  type Placeholder,
  placeholderCss,
  placeholderFor,
  type Rgb,
  rgbToOklch,
} from './placeholder.ts'
export {
  ALT_MIN_LENGTH,
  ALT_MIN_LETTERS,
  ALT_VIOLATION_RULES,
  type AltSubject,
  type AltViolation,
  type AltViolationRule,
  altViolations,
  assertAltAcceptable,
  assertSlotImagesPublishable,
  assertUploadAllowed,
  CROPPED_SLOT_NAMES,
  declaredCropRect,
  EDITABLE_SLOT_NAMES,
  type FocalPercent,
  isJunkAlt,
  isMediaSlotName,
  MEDIA_SLOT_LIST,
  MEDIA_SLOT_NAMES,
  type MediaSlot,
  mediaSlot,
  ORIGINAL_MIME_TYPES,
  type OriginalMimeType,
  type ProvisionalPlaceholder,
  PUBLICATION_REFUSAL_RULES,
  type PublicationRefusal,
  type PublicationRefusalRule,
  provisionalSlotPlaceholders,
  publicationRefusals,
  ratioDeviation,
  SLOT_RATIO_TOLERANCE,
  SLOT_REGISTRY,
  SLOT_VIOLATION_RULES,
  type SlotImageForPublication,
  type SlotPlaceholder,
  type SlotViolation,
  type SlotViolationRule,
  slotAspectRatio,
  slotPlaceholderColour,
  slotRatio,
  type UploadMeasurement,
  validateUpload,
} from './slots/index.ts'
export {
  createFakeMediaStorage,
  DEFAULT_OUTBOX,
  type FakeStorageOptions,
  PUT_LOG,
} from './storage/fake.ts'
export {
  derivativeHeaders,
  IMMUTABLE_CACHE_CONTROL,
  MEDIA_BUCKETS,
  type MediaBucket,
  type MediaStorage,
  PRIVATE_CACHE_CONTROL,
  type PutRequest,
  publicKeyFor,
  type ServedHeaders,
  type StoredObject,
} from './storage/port.ts'
export {
  assertContentHash,
  assertCroppedSlot,
  assertMediaId,
  CONTENT_HASH_LENGTH,
  CONTENT_HASH_PATTERN,
  CROPPED_SLOTS,
  DERIVATIVE_PATH_PATTERN,
  type DerivativeRef,
  derivativePath,
  MEDIA_ID_PATTERN,
  MEDIA_SLOTS,
  type MediaSlotName,
  originalKey,
  PRIVATE_ORIGINALS_PREFIX,
  PUBLIC_DERIVATIVE_PREFIX,
  parseDerivativePath,
} from './url.ts'
export {
  assertVideoSlot,
  type BuildVideoRenditionsInput,
  buildVideoRenditions,
  CENTRE_FOCAL as VIDEO_CENTRE_FOCAL,
  createFfmpegEncoder,
  describeMaster,
  detectFfmpegLicence,
  type EncodeRequest,
  FFMPEG_DECLARED_LICENCES,
  type FfmpegEncoderOptions,
  type FfmpegTools,
  type FfprobeStream,
  ffprobeStreams,
  type MasterDescription,
  type ResolveOptions,
  resolveFfmpeg,
  storeVideoMaster,
  type VideoBuildResult,
  type VideoEncoder,
  type VideoRenditionOutput,
} from './video/encode.ts'
export {
  type ArgvInput,
  assertMasterAcceptable,
  assertWithinHardStop,
  CODEC_ENCODER,
  FORBIDDEN_CONTAINERS,
  ffmpegArgv,
  filterGraphFor,
  fitsItsLevel,
  HERO_VIDEO_SLOT,
  type HeroVideoRelation,
  heroVideoRelation,
  isVideoMasterKey,
  isWithinBudget,
  MASTER_EXTENSIONS,
  MAX_MACROBLOCKS,
  MAX_MASTER_BYTES,
  MAX_MASTER_SECONDS,
  type MasterMeasurement,
  type MasterViolation,
  MIN_MASTER_HEIGHT,
  MIN_MASTER_WIDTH,
  macroblocksFor,
  masterViolations,
  maxMasterBytes,
  overBudgetMessage,
  PING_PONG_FILTER,
  PRIVATE_VIDEO_MASTER_PREFIX,
  REQUIRED_CODEC_TAG,
  type RenditionWeight,
  VIDEO_BUDGET_BYTES,
  VIDEO_CODECS,
  VIDEO_CONTAINER,
  VIDEO_CONTENT_TYPE,
  VIDEO_HARD_STOP_BYTES,
  VIDEO_MASTER_MIME_TYPES,
  VIDEO_MASTER_RULES,
  VIDEO_RENDITION_PATH_PATTERN,
  VIDEO_RENDITIONS,
  type VideoCodec,
  type VideoMasterRule,
  type VideoRendition,
  type VideoRenditionRef,
  videoMasterKey,
  videoRenditionPath,
  videoRenditionPaths,
} from './video/ladder.ts'
export {
  assertCodecTag,
  assertFaststart,
  assertPingPongDuration,
  compareFrames,
  type FaststartVerdict,
  type FrameComparison,
  findBoxPath,
  type Mp4Box,
  type Mp4Duration,
  type Mp4Probe,
  probeMp4,
  readBoxes,
  readCodecTag,
  readDuration,
  readFaststart,
  readTrackSummary,
  readY4mHeader,
  type TrackSummary,
  topLevelBoxOrder,
  type Y4mHeader,
} from './video/probe.ts'
export {
  MAX_STAND_IN_BYTES,
  rgbToYuv420,
  STAND_IN_MARKER,
  STAND_IN_ZOOM,
  type StandInMasterOptions,
  standInMasterY4m,
  type Yuv420Frame,
  y4mHeaderLine,
} from './video/stand-in.ts'
export { type StandInMp4Options, standInMp4 } from './video/testing.ts'
