/**
 * @berelax/shared — the only package every other package may depend on.
 * Types, branded primitives and error taxonomy. No I/O, no framework imports.
 */

export {
  ALERT_EVENT_AGGREGATE_TYPE,
  ALERT_IDS,
  ALERT_OBSERVATION_WINDOW_HOURS,
  ALERT_RAISED_EVENT,
  ALERT_REGISTRY,
  ALERT_SEVERITIES,
  ALERT_SLO_OPEN_QUESTION_ID,
  ALERT_SURFACES,
  ALERT_THRESHOLD_SETTING_KEYS,
  ALERT_THRESHOLD_UNREADABLE_EVENT,
  ALERT_THRESHOLDS_OPEN_QUESTION_ID,
  type AlertDefinition,
  type AlertId,
  type AlertRoute,
  type AlertSeverity,
  type AlertSlo,
  type AlertSurface,
  type AlertThreshold,
  AUTH_FAILURE_THRESHOLD_SETTING_KEY,
  AUTH_FAILURE_WINDOW_MINUTES,
  alertDefinition,
  JOB_FAILURE_THRESHOLD_SETTING_KEY,
  OUTBOX_LAG_THRESHOLD_SETTING_KEY,
  SEND_BACKLOG_THRESHOLD_SETTING_KEY,
  type SettingThreshold,
  STAFF_SESSION_REFUSED_ACTION,
  type StructuralThreshold,
  THRESHOLD_UNITS,
  type ThresholdUnit,
  UNDEFENDED_BY_DESIGN,
  type UndefendedCase,
} from './alerts/registry.ts'
export {
  ANALYTICS_CONSENT_COPY_OPEN_QUESTION,
  ANALYTICS_CONSENT_DECISIONS,
  ANALYTICS_CONSENT_PATH,
  ANALYTICS_CONSENT_REFUSALS,
  ANALYTICS_CONSENT_SURFACES,
  ANALYTICS_CONSENT_WORDING,
  type AnalyticsConsentDecision,
  type AnalyticsConsentDecisionBody,
  type AnalyticsConsentRefusal,
  type AnalyticsConsentSurface,
  analyticsConsentDecisionSchema,
  analyticsConsentShapeRefusal,
} from './analytics/analytics-consent.ts'
export {
  ANALYTICS_BREAKPOINT_BANDS,
  ANALYTICS_BREAKPOINTS,
  type AnalyticsBreakpoint,
  BREAKPOINT_UNKNOWN,
  breakpointFor,
  COLLECT_MAX_BATCH_EVENTS,
  COLLECT_MAX_BODY_BYTES,
  COLLECT_MAX_CLIENT_EVENT_ID_LENGTH,
  COLLECT_MAX_QUERY_LENGTH,
  COLLECT_MAX_REFERRER_LENGTH,
  COLLECT_PATH,
  COLLECT_REFUSALS,
  type CollectBatch,
  type CollectEvent,
  type CollectRefusal,
  collectBatchSchema,
  collectEventSchema,
  DEVICE_KINDS,
  type DeviceKind,
  deviceKindFor,
  isTradingDateBasis,
  SESSION_INACTIVITY_MS,
  TRADING_DATE_BASES,
  type TradingDateBasis,
} from './analytics/collect.ts'
export {
  ANALYTICS_CONSENT_COOKIE,
  ANALYTICS_STORAGE_SIGNAL,
  analyticsStorageGranted,
  CONSENT_MODE_SIGNALS,
  CONSENT_SIGNAL_SEPARATOR,
  type ConsentModeSignal,
  grantedConsentSignals,
} from './analytics/consent-signal.ts'
export {
  ANALYTICS_EVENT_NAMES,
  ANALYTICS_EVENT_SCHEMAS,
  ANALYTICS_OPEN_QUESTIONS,
  ANALYTICS_TAXONOMY_VERSION,
  ANALYTICS_WRITING_DIRECTIONS,
  type AnalyticsEvent,
  type AnalyticsEventName,
  type AnalyticsEventPayload,
  type AnalyticsWritingDirection,
  analyticsEventNameSchema,
  analyticsEventSchemaFor,
  CLS_VALUE_SCALE,
  CTA_TARGETS,
  type CtaTarget,
  FUNNEL_EXCLUSION_REASONS,
  FUNNEL_STAGES,
  FUNNEL_TERMINAL_STAGE,
  type FunnelExclusionReason,
  type FunnelStage,
  funnelExclusionReasonSchema,
  funnelStageRank,
  funnelStageSchema,
  funnelStagesAfter,
  isAnalyticsEventName,
  isFunnelExclusionReason,
  isFunnelStage,
  isTerminalFunnelStage,
  parseAnalyticsEvent,
  UnknownEventError,
  WEB_VITALS_IDENTITY_MAX,
  WEB_VITALS_IDENTITY_PATTERN,
  WEB_VITALS_MAX_VALUE,
  WEB_VITALS_METRICS,
  type WebVitalsMetric,
} from './analytics/taxonomy.ts'
export {
  CLINICAL_LINT_QUESTION_COPY_SETTING_KEY,
  CLINICAL_OPEN_QUESTIONS,
  CLINICAL_REAL_INTAKE_SETTING_KEY,
  CLINICAL_STEP_UP_WINDOW_CEILING_MINUTES,
  CLINICAL_STEP_UP_WINDOW_MINUTES,
  CLINICAL_STEP_UP_WINDOW_SETTING_KEY,
  CONTRAINDICATION_DERIVATION_VERSION,
  CONTRAINDICATION_ESCALATION_FLAG,
  CONTRAINDICATION_FLAG_KEYS,
  type ContraindicationFlagKey,
  type ContraindicationFlagSet,
  clinicalStepUpWindowSchema,
  contraindicationFlagSetSchema,
  PROVISIONAL_LINT_QUESTION_COPY,
  PROVISIONAL_REAL_INTAKE_PERMITTED,
} from './clinical.ts'
export {
  COMPLIANCE_CALENDAR_AGENT,
  DEFAULT_OBLIGATION_ESCALATION_OFFSETS_DAYS,
  DEFAULT_OBLIGATION_REMINDER_OFFSETS_DAYS,
  MAX_OBLIGATION_NOTICE_OFFSET_DAYS,
  MAX_OBLIGATION_NOTICE_OFFSETS,
  OBLIGATION_ESCALATION_OFFSETS_SETTING_KEY,
  OBLIGATION_REMINDER_OFFSETS_SETTING_KEY,
  REBUILD_OBLIGATION_NOTICES_JOB,
} from './compliance-notices.ts'
export {
  AI_CRAWLER_BOT_KINDS,
  AI_CRAWLER_FETCHERS,
  AI_CRAWLER_USER_AGENTS,
  AI_CRAWLERS,
  type AiCrawlerBotKind,
  type AiCrawlerFetcher,
  type AiCrawlerPolicyEntry,
  type AiCrawlerToken,
  type AiCrawlerUsageToken,
  CRAWLER_POLICY_OPEN_QUESTIONS,
} from './crawlers.ts'
export {
  CREDENTIAL_EXPIRING_SOON_SETTING_KEY,
  credentialExpiringSoonDaysSchema,
  PROVISIONAL_EXPIRING_SOON_DAYS,
} from './credential-window.ts'
export {
  GENDER_MATCHING_MODES,
  GENDER_MATCHING_SETTING_KEY,
  type GenderMatchingMode,
  genderMatchingMode,
  genderMatchingModeSchema,
  STRICT_GENDER_MATCHING,
} from './gender-matching.ts'
export {
  DEFAULT_GOOGLE_REAUTH_REPEAT_CAP,
  GOOGLE_REAUTH_REPEAT_CAP_SETTING_KEY,
  GOOGLE_REAUTH_SMS_SETTING_KEY,
  GOOGLE_REAUTH_TEMPLATE_KEY_LIST,
  GOOGLE_REAUTH_TEMPLATE_KEYS,
  MAX_GOOGLE_REAUTH_LADDER_STEPS,
  REAUTH_REASSURANCE_SENTENCE,
} from './google-reauth.ts'
export {
  DEFAULT_LLM_PROVIDER,
  LLM_PROVIDER_NAMES,
  LLM_PROVIDER_SETTING_KEY,
  type LlmProviderName,
  llmProviderName,
  llmProviderSchema,
} from './llm-provider.ts'
export {
  advanceMessageStatus,
  type Channel,
  DELIVERY_REPORTED_FAILED,
  HELD_MESSAGE_TERMINAL_REASONS,
  type HeldMessageTerminalReason,
  isSendableApproval,
  isTemplateApprovalTransition,
  isTerminalMessageStatus,
  MESSAGE_CHANNELS,
  MESSAGE_CLASSES,
  MESSAGE_FAILURE_REASONS,
  MESSAGE_ROW_FAILURE_REASONS,
  MESSAGE_STATUS_RANK,
  MESSAGE_STATUSES,
  MESSAGING_CONTROL_DIRECTIONS,
  MESSAGING_CONTROL_KEYS,
  type MessageChannel,
  type MessageClass,
  type MessageFailureReason,
  type MessageRowFailureReason,
  type MessageStatus,
  type MessagingControlDirection,
  type MessagingControlKey,
  type ReceiptIgnoredReason,
  type StatusAdvance,
  TEMPLATE_APPROVAL_STATES,
  TEMPLATE_APPROVAL_TRANSITIONS,
  type TemplateApprovalState,
} from './messaging.ts'
export {
  ERASURE_OVERRIDES_RETENTION_COLUMN,
  PRIVACY_OPEN_QUESTIONS,
  PROVISIONAL_RIGHTS_SLA_DAYS,
  PROVISIONAL_SUPERVISORY_AUTHORITY,
  RETENTION_PURGE_JOB,
  RIGHTS_BULK_EXPORT_EVENT,
  RIGHTS_REQUEST_TYPES,
  RIGHTS_SLA_DAYS_SETTING_KEY,
  RIGHTS_SLA_PROVENANCE,
  RIGHTS_SUPERVISORY_AUTHORITY_SETTING_KEY,
  type RightsRequestType,
  rightsSlaDaysSchema,
  rightsSupervisoryAuthoritySchema,
} from './privacy.ts'
export {
  DEFAULT_REMINDER_OFFSETS_HOURS,
  MAX_REMINDER_OFFSET_HOURS,
  MAX_REMINDER_OFFSETS,
  REBUILD_SCHEDULED_STEPS_JOB,
  REMINDER_OFFSETS_SETTING_KEY,
} from './reminders.ts'
export {
  BUSINESS_PROFILE_ACCESS_SETTING_KEY,
  configuredReviewLanguages,
  DETECTABLE_REVIEW_LANGUAGES,
  type DetectableReviewLanguage,
  MINIMUM_REVIEW_COOLING_OFF_HOURS,
  REVIEW_AUTOSEND_DISABLED,
  REVIEW_AUTOSEND_SETTING_KEY,
  REVIEW_AUTOSEND_SETTING_KEYS,
  REVIEW_COOLING_OFF_SETTING_KEY,
  REVIEW_COUNT_TRIPWIRE_AGENT,
  REVIEW_FALLBACK_TEMPLATE_KEY_LIST,
  REVIEW_FALLBACK_TEMPLATE_KEYS,
  REVIEW_MONDAY_NUDGE_AGENT,
  REVIEW_NUDGE_LOOKBACK_DAYS,
  REVIEW_REPLY_LANGUAGES_SETTING_KEY,
  REVIEW_REPLY_MODES,
  type ReviewAutosendSettingKey,
  type ReviewReplyMode,
  reviewAutosendEnabled,
  reviewAutosendEnabledSchema,
  reviewCoolingOffHours,
  reviewCoolingOffHoursSchema,
  reviewReplyLanguagesSchema,
  reviewReplyMode,
} from './review-autosend.ts'
export {
  type Assert,
  grossPriceFilsSchema,
  type PriceFreeShape,
  REQUIRED_SKILL_BY_STYLE,
  ROOM_TYPE_NAMES,
  type RoomTypeName,
  requiredSkillFor,
  roomTypeNameSchema,
  SERVICE_DURATIONS,
  SERVICE_SHAPES,
  type ServiceDuration,
  type ServiceInput,
  type ServiceResourceShapeInput,
  type ServiceShape,
  type ServiceSkillRequirement,
  type ServiceVariantInput,
  serviceDurationSchema,
  serviceResourceShapeSchema,
  serviceSchema,
  serviceShapeSchema,
  serviceVariantSchema,
  skillRequirements,
  THERAPIST_SKILLS,
  type TherapistSkill,
  TREATMENT_KEYS,
  TREATMENT_STYLES,
  type TreatmentKey,
  type TreatmentStyle,
  therapistSkillSchema,
  treatmentKeySchema,
  treatmentStyleSchema,
} from './schemas/catalogue.ts'
export {
  ANALYTICS_CONSENT_PURPOSE,
  CONSENT_ACTOR_KINDS,
  CONSENT_CAPTURE_SOURCES,
  CONSENT_CHANNELS,
  CONSENT_KINDS,
  CONSENT_LOCALES,
  CONSENT_PURPOSE_VOCABULARY,
  CONSENT_PURPOSES,
  type ConsentActorKind,
  type ConsentCaptureContext,
  type ConsentCaptureSource,
  type ConsentChannel,
  type ConsentKind,
  type ConsentLocale,
  type ConsentPurpose,
  type ConsentRecordInput,
  type ConsentWordingInput,
  consentCaptureContextSchema,
  consentRecordSchema,
  consentWordingSchema,
  isSendGatingPurpose,
  MAX_CONSENT_WORDING_LENGTH,
  PLACEHOLDER_MARKERS,
  SEND_GATING_CONSENT_PURPOSES,
  type SendGatingConsentPurpose,
} from './schemas/consent.ts'
export {
  FLOW_ANALYSIS_RULES,
  FLOW_BOOLEAN_CONDITION_FACTS,
  FLOW_CONDITION_BRANCHES,
  FLOW_CONDITION_FACTS,
  FLOW_CONDITION_OPERATORS,
  FLOW_DEFAULT_BRANCH,
  FLOW_DSL_RULES,
  FLOW_DSL_VERSION,
  FLOW_EXIT_REASONS,
  FLOW_NODE_KINDS,
  FLOW_RULES,
  FLOW_TERMINAL_NODE_KINDS,
  FLOW_TRIGGER_EVENTS,
  type FlowAnalysisRule,
  type FlowConditionFact,
  type FlowConditionOperator,
  type FlowDefinition,
  type FlowDslRule,
  type FlowEdge,
  type FlowExitReason,
  type FlowNode,
  type FlowNodeKind,
  type FlowRefusal,
  type FlowRule,
  type FlowTriggerEvent,
  flowDefinitionSchema,
  flowRuleMessage,
  isBooleanConditionFact,
  isFlowRule,
  MAX_FLOW_ACCUMULATED_DELAY_MINUTES,
  MAX_FLOW_NODES,
} from './schemas/flow.ts'
export {
  FLOW_END_REASONS,
  FLOW_ENROLMENT_OUTCOMES,
  FLOW_INTERPRETER_END_REASONS,
  FLOW_NODE_OUTCOMES,
  FLOW_RUN_MODES,
  FLOW_RUN_STATUSES,
  type FlowEndReason,
  type FlowEnrolmentOutcome,
  type FlowInterpreterEndReason,
  type FlowNodeOutcome,
  type FlowRunMode,
  type FlowRunStatus,
  isFlowEndReason,
  isTerminalFlowRunStatus,
  MAX_ACTIVE_ENROLMENTS_PER_FLOW,
  MAX_DRY_RUN_PROJECTED_ROWS,
  MAX_FLOW_NODE_EXECUTIONS,
} from './schemas/flow-run.ts'
export {
  isUnsuppressionSource,
  SUPPRESSION_ACTOR_KINDS,
  SUPPRESSION_KEY_KINDS,
  SUPPRESSION_KINDS,
  SUPPRESSION_SOURCES,
  type SuppressionActorKind,
  type SuppressionEntryInput,
  type SuppressionKeyKind,
  type SuppressionKind,
  type SuppressionSource,
  suppressionEntrySchema,
  UNSUPPRESSION_SOURCES,
  type UnsuppressionSource,
} from './schemas/suppression.ts'

/** Nominal typing helper, so an AppointmentId cannot be passed where a RoomId is wanted. */
export type Brand<T, B extends string> = T & { readonly __brand: B }

/**
 * The error taxonomy, re-exported from `./app-error.ts` where it now lives.
 *
 * Moved out of this file rather than declared in it, because a submodule of `shared` that needs to
 * SUBCLASS `AppError` — `analytics/taxonomy.ts` does, for `UnknownEventError` — would otherwise import
 * the barrel that re-exports it and close a cycle `no-circular` refuses. The names and the class
 * identity are unchanged, so every `import { AppError } from '@berelax/shared'` in the build still
 * resolves here and `isAppError` still answers true for every error raised anywhere.
 */
export { AppError, type ErrorKind, isAppError } from './app-error.ts'

/**
 * The CMS's schema name, from its own module. G-REV-02 moved it out of `payload.config.ts` because that file
 * is loaded by a strip-only loader, and `packages/db`'s catalogue probes need the name without loading the
 * CMS at all: `merge-participants.ts` excludes the schema by this constant rather than by the literal, so the
 * exclusion and the `schemaName` Payload is configured with cannot drift apart.
 */
export { CMS_SCHEMA } from './cms-schema.ts'
export {
  ACCOUNT_CODE_PATTERN,
  DEFAULT_GRATUITY_EXPENSE_ACCOUNT,
  DEFAULT_GRATUITY_LIABILITY_ACCOUNT,
  DEFAULT_GRATUITY_SETTLEMENT_PAYABLE_ACCOUNT,
  GRATUITY_ACCOUNTS_OPEN_QUESTION_ID,
  GRATUITY_EXPENSE_ACCOUNT_SETTING_KEY,
  GRATUITY_LIABILITY_ACCOUNT_SETTING_KEY,
  GRATUITY_RULE_OPEN_QUESTION_ID,
  GRATUITY_SETTLEMENT_PAYABLE_ACCOUNT_SETTING_KEY,
} from './gratuity-accounts.ts'
export {
  BREACH_CLOCK_OPEN_QUESTION_ID,
  BREACH_NOTIFICATION_HOURS_SETTING_KEY,
  BREACH_NOTIFICATION_OBLIGATION_KEY,
  BREACH_SUBJECT_NOTIFICATION_OBLIGATION_KEY,
  BREACH_THRESHOLD_OPEN_QUESTION_ID,
  FIELD_AUDIENCES,
  type FieldAudience,
  INCIDENT_CLASSES,
  INCIDENT_FIELDS,
  INCIDENT_NOTIFIED_PARTIES,
  INCIDENT_STRUCTURAL_COLUMNS,
  INCIDENT_TABLES,
  type IncidentClass,
  type IncidentField,
  type IncidentNotifiedParty,
  type IncidentTable,
  incidentFieldsFor,
  PERSONAL_DATA_BREACH,
} from './incident-register.ts'
export {
  PARALLEL_RUN_DECISIONS,
  PARALLEL_RUN_WINDOW_END_SETTING_KEY,
  PARALLEL_RUN_WINDOW_OPEN_QUESTION_ID,
  PARALLEL_RUN_WINDOW_SETTING_KEYS,
  PARALLEL_RUN_WINDOW_START_SETTING_KEY,
  type ParallelRunDecisionValue,
  PILOT_DEVICE_OPEN_QUESTION_ID,
  PILOT_FEEDBACK_CATEGORIES,
  PILOT_FEEDBACK_CATEGORY_VALUES,
  PILOT_FEEDBACK_FIX_CATEGORIES,
  PILOT_FIX_UNIT_PREFIX,
  PILOT_OPEN_QUESTION_ID,
  type PilotFeedbackCategoryDefinition,
  pilotFeedbackCategory,
  pilotFixUnitId,
  WALK_IN_SPEED_BUDGET_MS,
  WALK_IN_SPEED_PERCENTILE,
} from './parallel-run.ts'
export {
  addressLines,
  addressOneLine,
  directionsLinkFor,
  formatUaePhone,
  type MapTarget,
  mapLinkFor,
  type PostalAddress,
  telLinkFor,
  WHATSAPP_NUMBER_OPEN_QUESTION,
  type WhatsappLink,
  type WhatsappLinkRefusal,
  whatsappLinkFor,
} from './premises-links.ts'
export {
  PROCESSOR_AGREEMENT_OPEN_QUESTION_ID,
  PROCESSOR_CONFIG_KEYS,
  PROCESSOR_DATA_CLASSES,
  PROCESSOR_IDS,
  PROCESSOR_PURPOSES,
  PROCESSOR_REGISTER,
  PROCESSOR_RESIDENCY_OPEN_QUESTION_ID,
  type Processor,
  type ProcessorDataClass,
  type ProcessorPurpose,
  processorById,
  TRANSFER_BASES,
  type TransferBasis,
} from './processor-register.ts'
export {
  addressSchema,
  catalogueSchema,
  FACTS_SCHEMA_VERSION,
  type Facts,
  type FactsAddress,
  type FactsCatalogue,
  type FactsHours,
  type FactsHoursException,
  type FactsOpeningHoursDay,
  type FactsPhone,
  type FactsWhatsapp,
  factsSchema,
  filsStringSchema,
  geoSchema,
  hoursExceptionSchema,
  hoursSchema,
  isoDateSchema,
  localTimeSchema,
  openingHoursDaySchema,
  type ProvisionalFact,
  phoneSchema,
  priceOnRequestSchema,
  priceServiceSchema,
  priceVariantSchema,
  provisionalFactSchema,
  type UnansweredFact,
  unansweredFactSchema,
  whatsappSchema,
} from './schemas/facts.ts'
export {
  MANAGE_BOOKING_PATH_PREFIX,
  manageBookingLink,
  manageBookingPath,
  PREFERENCE_CENTRE_PATH,
  type PreferenceCentreLink,
  preferenceCentreLink,
  preferenceCentrePath,
  RECONNECT_SCREEN_PATH,
  reconnectLink,
  SITE_ORIGIN_ENV,
  SITE_ORIGIN_FALLBACK,
  siteOriginFrom,
} from './site-origin.ts'
export {
  FRONT_DESK_MIN_LEAD_SETTING_KEY,
  isWhatsappRefCode,
  normaliseWhatsappRefCode,
  PROVISIONAL_FRONT_DESK_MIN_LEAD_MINUTES,
  PROVISIONAL_WHATSAPP_REF_EXPECTED,
  PROVISIONAL_WHATSAPP_REF_TTL_DAYS,
  WHATSAPP_REF_ALPHABET,
  WHATSAPP_REF_CODE_CLASS,
  WHATSAPP_REF_CODE_HTML_PATTERN,
  WHATSAPP_REF_CODE_LENGTH,
  WHATSAPP_REF_CODE_PATTERN,
  WHATSAPP_REF_EXPECTED_SETTING_KEY,
  WHATSAPP_REF_INPUT_CLASS,
  WHATSAPP_REF_MESSAGE_PREFIX,
  WHATSAPP_REF_OPEN_QUESTION,
  WHATSAPP_REF_TTL_OPEN_QUESTION,
  WHATSAPP_REF_TTL_SETTING_KEY,
  whatsappRefCodeSchema,
  whatsappRefMessage,
} from './whatsapp-ref.ts'
export {
  PLACEHOLDER_WPS_AGENT_ID,
  PLACEHOLDER_WPS_EMPLOYER_ID,
  WPS_OPEN_QUESTION_ID,
} from './wps.ts'
