import { z } from 'zod'

/**
 * `agents.llm_provider`: the vocabulary, the schema and the reader.
 *
 * Here for the reason `review-autosend.ts` gives at length: three packages that may not import one
 * another read this value. `@berelax/config` declares what may be **written**, `@berelax/db` reads the
 * stored row, and `@berelax/providers` turns the name into an adapter. A list spelled in each of them is
 * a list that disagrees the day one of them changes.
 *
 * ## Why this reader is not biased to a default, unlike the auto-send floors
 *
 * Every normaliser in `review-autosend.ts` resolves an unreadable value to the **strictest** answer,
 * because there the permissive answer publishes a reply with nobody reading it. Here the analogous move
 * — resolving an unrecognised name to the local fake — would be worse than refusing: drafts would be
 * generated by a provider the owner did not choose and billed to an account they did not agree, and
 * nothing would say so. So {@link llmProviderName} answers `null` for anything it does not recognise and
 * the caller refuses. A refusal is visible: the agent run is recorded as failed, `last_success_at` is
 * left alone, and the watchdog reports the agent silent within two intervals (G-AGT-01).
 */

/** `agents.llm_provider`. One spelling for the registry, the reader and the adapter table. */
export const LLM_PROVIDER_SETTING_KEY = 'agents.llm_provider'

/**
 * The names the setting may hold.
 *
 * `fake` is the local deterministic adapter and the default. `deepseek` and `minimax` are the two
 * candidates docs/07 §4 names, and today they resolve to fakes — provider selection is a configuration
 * change either way, which is the whole contract (docs/12 §1.3). `claude` is declared because it is the
 * obvious third candidate and because an owner seeing it in the list and getting a clear refusal is
 * better than an owner not seeing it and being told the system cannot do it.
 */
export const LLM_PROVIDER_NAMES = ['fake', 'deepseek', 'minimax', 'claude'] as const
export type LlmProviderName = (typeof LLM_PROVIDER_NAMES)[number]

/** What the setting holds until an owner changes it. */
export const DEFAULT_LLM_PROVIDER: LlmProviderName = 'fake'

/** What may be WRITTEN into `agents.llm_provider`. */
export const llmProviderSchema = z.enum(LLM_PROVIDER_NAMES)

/** The stored value as a name this build declares, or `null`. Total over `unknown`. */
export function llmProviderName(value: unknown): LlmProviderName | null {
  return typeof value === 'string' && (LLM_PROVIDER_NAMES as readonly string[]).includes(value)
    ? (value as LlmProviderName)
    : null
}
