#!/usr/bin/env node
/**
 * Byte budgets for everything shipped to a browser or embedded in a document.
 *
 * A performance budget nobody measures is a paragraph in a design document. This measures, and it
 * fails — which is the only difference that matters, because payload weight never regresses in one
 * visible step. It regresses by eight kilobytes at a time, each individually reasonable, until the
 * page is twice the size and nobody can point at the commit.
 *
 * `build/budgets.json` carries a reason per entry, not just a number. A budget with no stated reason
 * gets raised the first time it fails, which makes it decoration.
 *
 * W-SYS adds the JavaScript bundles once `apps/web` exists. Everything listed here can regress today.
 */
import { readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { embeddedFontBytes } from '../packages/pdf/src/fonts.ts'

const ROOT = join(import.meta.dirname, '..')
const { budgets } = JSON.parse(readFileSync(join(ROOT, 'build', 'budgets.json'), 'utf8'))

const kb = (bytes) => `${(bytes / 1024).toFixed(1)}KB`

let failures = 0
let skipped = 0

for (const budget of budgets) {
  let actual
  if (budget.kind === 'fonts') {
    actual = embeddedFontBytes()
  } else {
    try {
      actual = statSync(join(ROOT, budget.path)).size
    } catch {
      if (budget.optional === true) {
        // Generated by `pnpm screens`, which CI runs before this. A developer who has not run it
        // locally should not get a failure about a file they were never asked to produce.
        console.log(`SKIP  ${budget.label.padEnd(42)} not built`)
        skipped += 1
        continue
      }
      console.error(`FAIL  ${budget.label.padEnd(42)} missing: ${budget.path}`)
      failures += 1
      continue
    }
  }

  const headroom = budget.maxBytes - actual
  const status = headroom >= 0 ? 'PASS' : 'FAIL'
  if (headroom < 0) failures += 1
  console.log(
    `${status}  ${budget.label.padEnd(42)} ${kb(actual).padStart(9)} of ${kb(budget.maxBytes).padStart(9)}` +
      `  (${headroom >= 0 ? `${kb(headroom)} left` : `${kb(-headroom)} over`})`,
  )
  if (headroom < 0) console.error(`      ${budget.why}`)
}

if (failures > 0) {
  console.error(
    `\n${failures} budget(s) breached. Raising the number is a decision with a reason, not a fix — ` +
      'the reason is in build/budgets.json beside it.',
  )
  process.exit(1)
}
console.log(`\n${budgets.length - skipped} budget(s) within limits.`)
