#!/usr/bin/env node
/**
 * Byte budgets for everything shipped to a browser or embedded in a document.
 *
 * A performance budget nobody measures is a paragraph in a design document. This measures, and it
 * fails — which is the only difference that matters, because payload weight never regresses in one
 * visible step. It regresses by eight kilobytes at a time, each individually reasonable, until the
 * page is twice the size and nobody can point at the commit.
 *
 * `build/budgets.json` carries a reason per entry, not just a number. A budget with no stated reason
 * gets raised the first time it fails, which makes it decoration.
 *
 * W-SYS adds the JavaScript bundles once `apps/web` exists. Everything listed here can regress today.
 */
import { readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { encodeRendition } from '../packages/media/src/derivatives.ts'
import { embeddedFontBytes } from '../packages/pdf/src/fonts.ts'

const ROOT = join(import.meta.dirname, '..')
const { budgets } = JSON.parse(readFileSync(join(ROOT, 'build', 'budgets.json'), 'utf8'))

const kb = (bytes) => `${(bytes / 1024).toFixed(1)}KB`

/**
 * The media manifest, for the focal point a derivative budget has to crop around.
 *
 * A budget measured on a centre crop would be measuring a file the site never serves: the portraits are
 * full-length shots whose subject sits in the top fifth, and the crop that keeps the face in frame is a
 * different set of pixels with a different byte count.
 */
const mediaAssets = JSON.parse(
  readFileSync(join(ROOT, 'assets', 'media', 'manifest.json'), 'utf8'),
).assets

/**
 * A `derivative` budget encodes the real original through the real encoder and measures the result.
 *
 * It is built rather than read off disk because no derivative is committed (`assets/media/README.md`) —
 * they are produced at deploy time. Measuring a checked-in copy would measure whatever was last committed,
 * which is the thing a budget is supposed to notice changing.
 *
 * `encodeRendition` is the function `buildDerivatives` itself calls. A second copy of the encoder settings
 * here would let this pass while the file the site serves is over.
 */
async function derivativeBytes(budget) {
  const relative = budget.source.replace(/^assets\/media\//, '')
  const asset = mediaAssets.find((candidate) => candidate.path === relative)
  if (asset === undefined) {
    throw new Error(`${budget.id}: ${budget.source} is not in the media manifest`)
  }
  const encoded = await encodeRendition({
    source: readFileSync(join(ROOT, budget.source)),
    crop: budget.crop,
    width: budget.width,
    format: budget.format,
    focal: { x: asset.focalX ?? 50, y: asset.focalY ?? 50 },
  })
  return encoded.length
}

let failures = 0
let skipped = 0

for (const budget of budgets) {
  let actual
  if (budget.kind === 'fonts') {
    actual = embeddedFontBytes()
  } else if (budget.kind === 'derivative') {
    actual = await derivativeBytes(budget)
  } else {
    try {
      actual = statSync(join(ROOT, budget.path)).size
    } catch {
      if (budget.optional === true) {
        // Generated by `pnpm screens`, which CI runs before this. A developer who has not run it
        // locally should not get a failure about a file they were never asked to produce.
        console.log(`SKIP  ${budget.label.padEnd(42)} not built`)
        skipped += 1
        continue
      }
      console.error(`FAIL  ${budget.label.padEnd(42)} missing: ${budget.path}`)
      failures += 1
      continue
    }
  }

  const headroom = budget.maxBytes - actual
  const status = headroom >= 0 ? 'PASS' : 'FAIL'
  if (headroom < 0) failures += 1
  console.log(
    `${status}  ${budget.label.padEnd(42)} ${kb(actual).padStart(9)} of ${kb(budget.maxBytes).padStart(9)}` +
      `  (${headroom >= 0 ? `${kb(headroom)} left` : `${kb(-headroom)} over`})`,
  )
  if (headroom < 0) {
    // The rule name and the exact byte count, in that order. `scripts/test-gates.mjs` asserts a known-bad
    // fixture was rejected *by this rule* rather than by a missing file or a thrown encoder — the ADR 0003
    // failure mode — and the number has to be the measurement rather than a rounded kilobyte, because the
    // first question anybody asks of a breached budget is by how much.
    console.error(
      `      [over-budget] ${budget.id}: measured ${actual} bytes against a budget of ` +
        `${budget.maxBytes} bytes`,
    )
    console.error(`      ${budget.why}`)
  }
}

if (failures > 0) {
  console.error(
    `\n${failures} budget(s) breached. Raising the number is a decision with a reason, not a fix — ` +
      'the reason is in build/budgets.json beside it.',
  )
  process.exit(1)
}
console.log(`\n${budgets.length - skipped} budget(s) within limits.`)
