import { createConnection, type Sql } from '@berelax/db'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { FIXTURE_CLOSE, FIXTURE_OPEN } from './clock.ts'
import { loadSalon, orderedLoaders, registerLoader } from './load.ts'
import { generateSalon } from './salon.ts'

/**
 * H03 — seeding twice from clean must produce the same rows.
 *
 * Idempotence is the acceptance criterion and it is also the thing that makes `pnpm seed` safe to
 * run a second time when somebody is not sure whether the first one worked. A loader that appends
 * passes a single run and fails the second, which is the run nobody tests.
 */
const url = process.env['TEST_DATABASE_URL'] ?? process.env['DATABASE_URL']
if (!url)
  throw new Error('TEST_DATABASE_URL or DATABASE_URL is required — integration tests do not skip.')

let sql: Sql
const salon = generateSalon()

beforeAll(() => {
  sql = createConnection({ url, max: 2 })
})

afterAll(async () => {
  await sql?.end({ timeout: 5 })
})

async function snapshot() {
  const premises = await sql<{ row: string }[]>`
    select (display_name || '|' || address_line_1 || '|' || area) as row from premises order by id
  `
  const hours = await sql<{ row: string }[]>`
    select (day_of_week || '|' || open_time::text || '|' || close_time::text || '|' || crosses_midnight::text) as row
    from premises_hours order by day_of_week
  `
  const settings = await sql<{ row: string }[]>`
    select (key || '|' || value::text) as row from app_setting
    where key in ('booking.turnaround_minutes_standard','booking.turnaround_minutes_wet','packages.default_validity_months')
    order by key
  `
  return {
    premises: premises.map((r) => r.row),
    hours: hours.map((r) => r.row),
    settings: settings.map((r) => r.row),
  }
}

describe('loader ordering', () => {
  it('orders loaders by their declared dependencies', () => {
    const names = orderedLoaders().map((loader) => loader.name)
    expect(names.indexOf('premises')).toBeLessThan(names.indexOf('settings'))
  })

  it('refuses a duplicate registration rather than shadowing one silently', () => {
    expect(() => registerLoader({ name: 'premises', after: [], load: async () => 0 })).toThrow(
      /already registered/,
    )
  })
})

describe('seeding is idempotent', () => {
  it('produces identical rows when run twice from clean', async () => {
    await sql`delete from premises_hours`
    await sql`delete from premises`

    await loadSalon(sql, salon)
    const first = await snapshot()

    await loadSalon(sql, salon)
    const second = await snapshot()

    expect(second).toEqual(first)
  })

  it('seeds the trading hours that make business_day mean something', async () => {
    await loadSalon(sql, salon)
    const rows = await sql<{ open_time: string; close_time: string; crosses_midnight: boolean }[]>`
      select open_time::text, close_time::text, crosses_midnight from premises_hours order by day_of_week
    `
    expect(rows).toHaveLength(7)
    for (const row of rows) {
      expect(row.open_time).toBe(`${FIXTURE_OPEN}:00`)
      expect(row.close_time).toBe(`${FIXTURE_CLOSE}:00`)
      // Generated by the database from the times, so no caller can disagree with it.
      expect(row.crosses_midnight).toBe(true)
    }
  })

  it('removes a day taken out of the fixture, rather than leaving it behind', async () => {
    await loadSalon(sql, salon)
    await sql`insert into premises_hours (day_of_week, open_time, close_time) values (0, time '09:00', time '17:00') on conflict do nothing`
    const before = await sql<{ n: string }[]>`select count(*)::text as n from premises_hours`
    await loadSalon(sql, salon)
    const after = await sql<{ n: string }[]>`select count(*)::text as n from premises_hours`
    expect(Number(after[0]?.n)).toBeLessThanOrEqual(Number(before[0]?.n))
    expect(after[0]?.n).toBe('7')
  })

  it('writes settings through the store, so the change carries an audit trail', async () => {
    const before = await sql<{ n: string }[]>`select count(*)::text as n from app_setting_history`
    await sql`update app_setting set value = '99'::jsonb, updated_by = 'test' where key = 'booking.turnaround_minutes_standard'`
    await loadSalon(sql, salon)
    const after = await sql<{ n: string }[]>`select count(*)::text as n from app_setting_history`
    // app_setting_history is append-only (ADR 0008), so assert the delta rather than a total.
    expect(Number(after[0]?.n)).toBeGreaterThan(Number(before[0]?.n))
    const [row] = await sql<{ value: string }[]>`
      select value::text as value from app_setting where key = 'booking.turnaround_minutes_standard'
    `
    expect(row?.value).toBe('15')
  })
})
