import type { Sql } from '@berelax/db'
import { assertRelationName } from './provenance.ts'

/**
 * The two checksums every claim in H-MIG-01 is asserted by, and why there are exactly two.
 *
 * Both are thin wrappers over `import_staging.content_checksum`, which lives in the database so that the
 * framework's report and every suite compute the SAME number. Two implementations of one checksum is two
 * answers to "did this table change", and the first time they disagree the suite will be believed.
 *
 * **{@link exactChecksum} covers every column**, and it is the idempotence claim: importing the same source
 * file twice must produce zero new and zero changed rows, so not even a generated id may move.
 *
 * **{@link contentChecksum} excludes the columns a second run cannot reproduce**, and it is the
 * resumability claim: a killed and resumed import reaches the same final STATE as an uninterrupted one, and
 * those two runs differ in every `uuid_generate_v7()` and every `now()`. Comparing the bytes there would
 * fail for a reason that has nothing to do with the claim; comparing the content is the claim.
 *
 * Keeping them as two named functions rather than one with a flag is deliberate. A caller has to say which
 * of the two claims it is making, and a boolean at a call site does not read as a claim — while an
 * exclusion list spelled out at each call site is the second statement of a fact this repository keeps
 * paying for.
 */

/**
 * The columns a second import of the same rows cannot reproduce byte for byte.
 *
 * Every one of them is generated by the database and none of them is content: `uuid_generate_v7()` embeds
 * the millisecond it ran in, and the five timestamps are `now()`. A column is in this list because its
 * value is a fact about WHEN the import ran, which is exactly what the resumability comparison is supposed
 * to ignore.
 *
 * It is a fixed list rather than a derivation from column defaults, because a derivation would silently
 * widen: a target table that later gives a genuine content column a default would drop out of the
 * comparison with nothing saying so. A name added here is a decision somebody makes.
 */
export const GENERATED_COLUMNS: readonly string[] = Object.freeze([
  'id',
  'created_at',
  'updated_at',
  'recorded_at',
  'applied_at',
  'started_at',
  'finished_at',
])

/**
 * md5 over every column of a relation. An EMPTY relation answers `empty:<relation>` and not `md5('')`, so
 * "no rows" and "no columns were read" are different answers — the second is refused outright (ZY197).
 */
export async function exactChecksum(sql: Sql, relation: string): Promise<string> {
  const rows = await sql<{ checksum: string }[]>`
    select import_staging.content_checksum(${assertRelationName(relation)}::regclass) as checksum
  `
  return rows[0]?.checksum ?? ''
}

/** md5 over a relation's content, with {@link GENERATED_COLUMNS} excluded. */
export async function contentChecksum(
  sql: Sql,
  relation: string,
  exclude: readonly string[] = GENERATED_COLUMNS,
): Promise<string> {
  const rows = await sql<{ checksum: string }[]>`
    select import_staging.content_checksum(
             ${assertRelationName(relation)}::regclass,
             ${[...exclude]}::text[]
           ) as checksum
  `
  return rows[0]?.checksum ?? ''
}
